// Code generated by ent, DO NOT EDIT.

package step

import (
	"fmt"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the step type in the database.
	Label = "step"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDateCreated holds the string denoting the date_created field in the database.
	FieldDateCreated = "date_created"
	// FieldDateUpdated holds the string denoting the date_updated field in the database.
	FieldDateUpdated = "date_updated"
	// FieldWorkflowID holds the string denoting the workflow_id field in the database.
	FieldWorkflowID = "workflow_id"
	// FieldStepTypeID holds the string denoting the step_type_id field in the database.
	FieldStepTypeID = "step_type_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldConfig holds the string denoting the config field in the database.
	FieldConfig = "config"
	// FieldPositionX holds the string denoting the position_x field in the database.
	FieldPositionX = "position_x"
	// FieldPositionY holds the string denoting the position_y field in the database.
	FieldPositionY = "position_y"
	// FieldInputMapping holds the string denoting the input_mapping field in the database.
	FieldInputMapping = "input_mapping"
	// FieldTimeoutSeconds holds the string denoting the timeout_seconds field in the database.
	FieldTimeoutSeconds = "timeout_seconds"
	// FieldRetryCount holds the string denoting the retry_count field in the database.
	FieldRetryCount = "retry_count"
	// FieldRetryBackoff holds the string denoting the retry_backoff field in the database.
	FieldRetryBackoff = "retry_backoff"
	// FieldRetryDelayMs holds the string denoting the retry_delay_ms field in the database.
	FieldRetryDelayMs = "retry_delay_ms"
	// EdgeWorkflow holds the string denoting the workflow edge name in mutations.
	EdgeWorkflow = "workflow"
	// EdgeStepType holds the string denoting the step_type edge name in mutations.
	EdgeStepType = "step_type"
	// EdgeSourceEdges holds the string denoting the source_edges edge name in mutations.
	EdgeSourceEdges = "source_edges"
	// EdgeTargetEdges holds the string denoting the target_edges edge name in mutations.
	EdgeTargetEdges = "target_edges"
	// EdgeStepExecutions holds the string denoting the step_executions edge name in mutations.
	EdgeStepExecutions = "step_executions"
	// Table holds the table name of the step in the database.
	Table = "steps"
	// WorkflowTable is the table that holds the workflow relation/edge.
	WorkflowTable = "steps"
	// WorkflowInverseTable is the table name for the Workflow entity.
	// It exists in this package in order to avoid circular dependency with the "workflow" package.
	WorkflowInverseTable = "workflows"
	// WorkflowColumn is the table column denoting the workflow relation/edge.
	WorkflowColumn = "workflow_id"
	// StepTypeTable is the table that holds the step_type relation/edge.
	StepTypeTable = "steps"
	// StepTypeInverseTable is the table name for the StepType entity.
	// It exists in this package in order to avoid circular dependency with the "steptype" package.
	StepTypeInverseTable = "step_types"
	// StepTypeColumn is the table column denoting the step_type relation/edge.
	StepTypeColumn = "step_type_id"
	// SourceEdgesTable is the table that holds the source_edges relation/edge.
	SourceEdgesTable = "edges"
	// SourceEdgesInverseTable is the table name for the Edge entity.
	// It exists in this package in order to avoid circular dependency with the "edge" package.
	SourceEdgesInverseTable = "edges"
	// SourceEdgesColumn is the table column denoting the source_edges relation/edge.
	SourceEdgesColumn = "source_step_id"
	// TargetEdgesTable is the table that holds the target_edges relation/edge.
	TargetEdgesTable = "edges"
	// TargetEdgesInverseTable is the table name for the Edge entity.
	// It exists in this package in order to avoid circular dependency with the "edge" package.
	TargetEdgesInverseTable = "edges"
	// TargetEdgesColumn is the table column denoting the target_edges relation/edge.
	TargetEdgesColumn = "target_step_id"
	// StepExecutionsTable is the table that holds the step_executions relation/edge.
	StepExecutionsTable = "step_executions"
	// StepExecutionsInverseTable is the table name for the StepExecution entity.
	// It exists in this package in order to avoid circular dependency with the "stepexecution" package.
	StepExecutionsInverseTable = "step_executions"
	// StepExecutionsColumn is the table column denoting the step_executions relation/edge.
	StepExecutionsColumn = "step_id"
)

// Columns holds all SQL columns for step fields.
var Columns = []string{
	FieldID,
	FieldDateCreated,
	FieldDateUpdated,
	FieldWorkflowID,
	FieldStepTypeID,
	FieldName,
	FieldDescription,
	FieldConfig,
	FieldPositionX,
	FieldPositionY,
	FieldInputMapping,
	FieldTimeoutSeconds,
	FieldRetryCount,
	FieldRetryBackoff,
	FieldRetryDelayMs,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "react-go-workflow/ent/runtime"
var (
	Hooks [2]ent.Hook
	// DefaultDateCreated holds the default value on creation for the "date_created" field.
	DefaultDateCreated func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// DefaultPositionX holds the default value on creation for the "position_x" field.
	DefaultPositionX float64
	// DefaultPositionY holds the default value on creation for the "position_y" field.
	DefaultPositionY float64
	// DefaultTimeoutSeconds holds the default value on creation for the "timeout_seconds" field.
	DefaultTimeoutSeconds int
	// DefaultRetryCount holds the default value on creation for the "retry_count" field.
	DefaultRetryCount int
	// DefaultRetryDelayMs holds the default value on creation for the "retry_delay_ms" field.
	DefaultRetryDelayMs int
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// RetryBackoff defines the type for the "retry_backoff" enum field.
type RetryBackoff string

// RetryBackoffNone is the default value of the RetryBackoff enum.
const DefaultRetryBackoff = RetryBackoffNone

// RetryBackoff values.
const (
	RetryBackoffNone        RetryBackoff = "none"
	RetryBackoffFixed       RetryBackoff = "fixed"
	RetryBackoffExponential RetryBackoff = "exponential"
)

func (rb RetryBackoff) String() string {
	return string(rb)
}

// RetryBackoffValidator is a validator for the "retry_backoff" field enum values. It is called by the builders before save.
func RetryBackoffValidator(rb RetryBackoff) error {
	switch rb {
	case RetryBackoffNone, RetryBackoffFixed, RetryBackoffExponential:
		return nil
	default:
		return fmt.Errorf("step: invalid enum value for retry_backoff field: %q", rb)
	}
}

// OrderOption defines the ordering options for the Step queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDateCreated orders the results by the date_created field.
func ByDateCreated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateCreated, opts...).ToFunc()
}

// ByDateUpdated orders the results by the date_updated field.
func ByDateUpdated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateUpdated, opts...).ToFunc()
}

// ByWorkflowID orders the results by the workflow_id field.
func ByWorkflowID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkflowID, opts...).ToFunc()
}

// ByStepTypeID orders the results by the step_type_id field.
func ByStepTypeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStepTypeID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByPositionX orders the results by the position_x field.
func ByPositionX(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPositionX, opts...).ToFunc()
}

// ByPositionY orders the results by the position_y field.
func ByPositionY(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPositionY, opts...).ToFunc()
}

// ByTimeoutSeconds orders the results by the timeout_seconds field.
func ByTimeoutSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimeoutSeconds, opts...).ToFunc()
}

// ByRetryCount orders the results by the retry_count field.
func ByRetryCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRetryCount, opts...).ToFunc()
}

// ByRetryBackoff orders the results by the retry_backoff field.
func ByRetryBackoff(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRetryBackoff, opts...).ToFunc()
}

// ByRetryDelayMs orders the results by the retry_delay_ms field.
func ByRetryDelayMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRetryDelayMs, opts...).ToFunc()
}

// ByWorkflowField orders the results by workflow field.
func ByWorkflowField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newWorkflowStep(), sql.OrderByField(field, opts...))
	}
}

// ByStepTypeField orders the results by step_type field.
func ByStepTypeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStepTypeStep(), sql.OrderByField(field, opts...))
	}
}

// BySourceEdgesCount orders the results by source_edges count.
func BySourceEdgesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSourceEdgesStep(), opts...)
	}
}

// BySourceEdges orders the results by source_edges terms.
func BySourceEdges(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSourceEdgesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTargetEdgesCount orders the results by target_edges count.
func ByTargetEdgesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTargetEdgesStep(), opts...)
	}
}

// ByTargetEdges orders the results by target_edges terms.
func ByTargetEdges(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTargetEdgesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByStepExecutionsCount orders the results by step_executions count.
func ByStepExecutionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newStepExecutionsStep(), opts...)
	}
}

// ByStepExecutions orders the results by step_executions terms.
func ByStepExecutions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStepExecutionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newWorkflowStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(WorkflowInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, WorkflowTable, WorkflowColumn),
	)
}
func newStepTypeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StepTypeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, StepTypeTable, StepTypeColumn),
	)
}
func newSourceEdgesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SourceEdgesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SourceEdgesTable, SourceEdgesColumn),
	)
}
func newTargetEdgesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TargetEdgesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TargetEdgesTable, TargetEdgesColumn),
	)
}
func newStepExecutionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StepExecutionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, StepExecutionsTable, StepExecutionsColumn),
	)
}
