// Code generated by ent, DO NOT EDIT.

package workflowexecution

import (
	"react-go-workflow/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldLTE(FieldID, id))
}

// DateCreated applies equality check predicate on the "date_created" field. It's identical to DateCreatedEQ.
func DateCreated(v time.Time) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldEQ(FieldDateCreated, v))
}

// DateUpdated applies equality check predicate on the "date_updated" field. It's identical to DateUpdatedEQ.
func DateUpdated(v time.Time) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldEQ(FieldDateUpdated, v))
}

// WorkflowID applies equality check predicate on the "workflow_id" field. It's identical to WorkflowIDEQ.
func WorkflowID(v uuid.UUID) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldEQ(FieldWorkflowID, v))
}

// WorkflowVersionID applies equality check predicate on the "workflow_version_id" field. It's identical to WorkflowVersionIDEQ.
func WorkflowVersionID(v uuid.UUID) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldEQ(FieldWorkflowVersionID, v))
}

// Error applies equality check predicate on the "error" field. It's identical to ErrorEQ.
func Error(v string) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldEQ(FieldError, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldEQ(FieldStartedAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldEQ(FieldCompletedAt, v))
}

// DateCreatedEQ applies the EQ predicate on the "date_created" field.
func DateCreatedEQ(v time.Time) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldEQ(FieldDateCreated, v))
}

// DateCreatedNEQ applies the NEQ predicate on the "date_created" field.
func DateCreatedNEQ(v time.Time) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldNEQ(FieldDateCreated, v))
}

// DateCreatedIn applies the In predicate on the "date_created" field.
func DateCreatedIn(vs ...time.Time) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldIn(FieldDateCreated, vs...))
}

// DateCreatedNotIn applies the NotIn predicate on the "date_created" field.
func DateCreatedNotIn(vs ...time.Time) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldNotIn(FieldDateCreated, vs...))
}

// DateCreatedGT applies the GT predicate on the "date_created" field.
func DateCreatedGT(v time.Time) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldGT(FieldDateCreated, v))
}

// DateCreatedGTE applies the GTE predicate on the "date_created" field.
func DateCreatedGTE(v time.Time) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldGTE(FieldDateCreated, v))
}

// DateCreatedLT applies the LT predicate on the "date_created" field.
func DateCreatedLT(v time.Time) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldLT(FieldDateCreated, v))
}

// DateCreatedLTE applies the LTE predicate on the "date_created" field.
func DateCreatedLTE(v time.Time) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldLTE(FieldDateCreated, v))
}

// DateUpdatedEQ applies the EQ predicate on the "date_updated" field.
func DateUpdatedEQ(v time.Time) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldEQ(FieldDateUpdated, v))
}

// DateUpdatedNEQ applies the NEQ predicate on the "date_updated" field.
func DateUpdatedNEQ(v time.Time) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldNEQ(FieldDateUpdated, v))
}

// DateUpdatedIn applies the In predicate on the "date_updated" field.
func DateUpdatedIn(vs ...time.Time) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldIn(FieldDateUpdated, vs...))
}

// DateUpdatedNotIn applies the NotIn predicate on the "date_updated" field.
func DateUpdatedNotIn(vs ...time.Time) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldNotIn(FieldDateUpdated, vs...))
}

// DateUpdatedGT applies the GT predicate on the "date_updated" field.
func DateUpdatedGT(v time.Time) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldGT(FieldDateUpdated, v))
}

// DateUpdatedGTE applies the GTE predicate on the "date_updated" field.
func DateUpdatedGTE(v time.Time) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldGTE(FieldDateUpdated, v))
}

// DateUpdatedLT applies the LT predicate on the "date_updated" field.
func DateUpdatedLT(v time.Time) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldLT(FieldDateUpdated, v))
}

// DateUpdatedLTE applies the LTE predicate on the "date_updated" field.
func DateUpdatedLTE(v time.Time) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldLTE(FieldDateUpdated, v))
}

// DateUpdatedIsNil applies the IsNil predicate on the "date_updated" field.
func DateUpdatedIsNil() predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldIsNull(FieldDateUpdated))
}

// DateUpdatedNotNil applies the NotNil predicate on the "date_updated" field.
func DateUpdatedNotNil() predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldNotNull(FieldDateUpdated))
}

// WorkflowIDEQ applies the EQ predicate on the "workflow_id" field.
func WorkflowIDEQ(v uuid.UUID) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldEQ(FieldWorkflowID, v))
}

// WorkflowIDNEQ applies the NEQ predicate on the "workflow_id" field.
func WorkflowIDNEQ(v uuid.UUID) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldNEQ(FieldWorkflowID, v))
}

// WorkflowIDIn applies the In predicate on the "workflow_id" field.
func WorkflowIDIn(vs ...uuid.UUID) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldIn(FieldWorkflowID, vs...))
}

// WorkflowIDNotIn applies the NotIn predicate on the "workflow_id" field.
func WorkflowIDNotIn(vs ...uuid.UUID) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldNotIn(FieldWorkflowID, vs...))
}

// WorkflowVersionIDEQ applies the EQ predicate on the "workflow_version_id" field.
func WorkflowVersionIDEQ(v uuid.UUID) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldEQ(FieldWorkflowVersionID, v))
}

// WorkflowVersionIDNEQ applies the NEQ predicate on the "workflow_version_id" field.
func WorkflowVersionIDNEQ(v uuid.UUID) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldNEQ(FieldWorkflowVersionID, v))
}

// WorkflowVersionIDIn applies the In predicate on the "workflow_version_id" field.
func WorkflowVersionIDIn(vs ...uuid.UUID) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldIn(FieldWorkflowVersionID, vs...))
}

// WorkflowVersionIDNotIn applies the NotIn predicate on the "workflow_version_id" field.
func WorkflowVersionIDNotIn(vs ...uuid.UUID) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldNotIn(FieldWorkflowVersionID, vs...))
}

// WorkflowVersionIDIsNil applies the IsNil predicate on the "workflow_version_id" field.
func WorkflowVersionIDIsNil() predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldIsNull(FieldWorkflowVersionID))
}

// WorkflowVersionIDNotNil applies the NotNil predicate on the "workflow_version_id" field.
func WorkflowVersionIDNotNil() predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldNotNull(FieldWorkflowVersionID))
}

// TriggerTypeEQ applies the EQ predicate on the "trigger_type" field.
func TriggerTypeEQ(v TriggerType) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldEQ(FieldTriggerType, v))
}

// TriggerTypeNEQ applies the NEQ predicate on the "trigger_type" field.
func TriggerTypeNEQ(v TriggerType) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldNEQ(FieldTriggerType, v))
}

// TriggerTypeIn applies the In predicate on the "trigger_type" field.
func TriggerTypeIn(vs ...TriggerType) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldIn(FieldTriggerType, vs...))
}

// TriggerTypeNotIn applies the NotIn predicate on the "trigger_type" field.
func TriggerTypeNotIn(vs ...TriggerType) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldNotIn(FieldTriggerType, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldNotIn(FieldStatus, vs...))
}

// InputIsNil applies the IsNil predicate on the "input" field.
func InputIsNil() predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldIsNull(FieldInput))
}

// InputNotNil applies the NotNil predicate on the "input" field.
func InputNotNil() predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldNotNull(FieldInput))
}

// OutputIsNil applies the IsNil predicate on the "output" field.
func OutputIsNil() predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldIsNull(FieldOutput))
}

// OutputNotNil applies the NotNil predicate on the "output" field.
func OutputNotNil() predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldNotNull(FieldOutput))
}

// ErrorEQ applies the EQ predicate on the "error" field.
func ErrorEQ(v string) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldEQ(FieldError, v))
}

// ErrorNEQ applies the NEQ predicate on the "error" field.
func ErrorNEQ(v string) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldNEQ(FieldError, v))
}

// ErrorIn applies the In predicate on the "error" field.
func ErrorIn(vs ...string) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldIn(FieldError, vs...))
}

// ErrorNotIn applies the NotIn predicate on the "error" field.
func ErrorNotIn(vs ...string) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldNotIn(FieldError, vs...))
}

// ErrorGT applies the GT predicate on the "error" field.
func ErrorGT(v string) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldGT(FieldError, v))
}

// ErrorGTE applies the GTE predicate on the "error" field.
func ErrorGTE(v string) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldGTE(FieldError, v))
}

// ErrorLT applies the LT predicate on the "error" field.
func ErrorLT(v string) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldLT(FieldError, v))
}

// ErrorLTE applies the LTE predicate on the "error" field.
func ErrorLTE(v string) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldLTE(FieldError, v))
}

// ErrorContains applies the Contains predicate on the "error" field.
func ErrorContains(v string) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldContains(FieldError, v))
}

// ErrorHasPrefix applies the HasPrefix predicate on the "error" field.
func ErrorHasPrefix(v string) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldHasPrefix(FieldError, v))
}

// ErrorHasSuffix applies the HasSuffix predicate on the "error" field.
func ErrorHasSuffix(v string) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldHasSuffix(FieldError, v))
}

// ErrorIsNil applies the IsNil predicate on the "error" field.
func ErrorIsNil() predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldIsNull(FieldError))
}

// ErrorNotNil applies the NotNil predicate on the "error" field.
func ErrorNotNil() predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldNotNull(FieldError))
}

// ErrorEqualFold applies the EqualFold predicate on the "error" field.
func ErrorEqualFold(v string) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldEqualFold(FieldError, v))
}

// ErrorContainsFold applies the ContainsFold predicate on the "error" field.
func ErrorContainsFold(v string) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldContainsFold(FieldError, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldNotNull(FieldStartedAt))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.FieldNotNull(FieldCompletedAt))
}

// HasWorkflow applies the HasEdge predicate on the "workflow" edge.
func HasWorkflow() predicate.WorkflowExecution {
	return predicate.WorkflowExecution(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, WorkflowTable, WorkflowColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWorkflowWith applies the HasEdge predicate on the "workflow" edge with a given conditions (other predicates).
func HasWorkflowWith(preds ...predicate.Workflow) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(func(s *sql.Selector) {
		step := newWorkflowStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasWorkflowVersion applies the HasEdge predicate on the "workflow_version" edge.
func HasWorkflowVersion() predicate.WorkflowExecution {
	return predicate.WorkflowExecution(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, WorkflowVersionTable, WorkflowVersionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWorkflowVersionWith applies the HasEdge predicate on the "workflow_version" edge with a given conditions (other predicates).
func HasWorkflowVersionWith(preds ...predicate.WorkflowVersion) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(func(s *sql.Selector) {
		step := newWorkflowVersionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasStepExecutions applies the HasEdge predicate on the "step_executions" edge.
func HasStepExecutions() predicate.WorkflowExecution {
	return predicate.WorkflowExecution(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, StepExecutionsTable, StepExecutionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStepExecutionsWith applies the HasEdge predicate on the "step_executions" edge with a given conditions (other predicates).
func HasStepExecutionsWith(preds ...predicate.StepExecution) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(func(s *sql.Selector) {
		step := newStepExecutionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasNotifications applies the HasEdge predicate on the "notifications" edge.
func HasNotifications() predicate.WorkflowExecution {
	return predicate.WorkflowExecution(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, NotificationsTable, NotificationsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNotificationsWith applies the HasEdge predicate on the "notifications" edge with a given conditions (other predicates).
func HasNotificationsWith(preds ...predicate.Notification) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(func(s *sql.Selector) {
		step := newNotificationsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WorkflowExecution) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WorkflowExecution) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WorkflowExecution) predicate.WorkflowExecution {
	return predicate.WorkflowExecution(sql.NotPredicates(p))
}
