// Code generated by ent, DO NOT EDIT.

package edge

import (
	"fmt"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the edge type in the database.
	Label = "edge"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDateCreated holds the string denoting the date_created field in the database.
	FieldDateCreated = "date_created"
	// FieldDateUpdated holds the string denoting the date_updated field in the database.
	FieldDateUpdated = "date_updated"
	// FieldWorkflowID holds the string denoting the workflow_id field in the database.
	FieldWorkflowID = "workflow_id"
	// FieldSourceStepID holds the string denoting the source_step_id field in the database.
	FieldSourceStepID = "source_step_id"
	// FieldTargetStepID holds the string denoting the target_step_id field in the database.
	FieldTargetStepID = "target_step_id"
	// FieldSourceOutput holds the string denoting the source_output field in the database.
	FieldSourceOutput = "source_output"
	// FieldTargetInput holds the string denoting the target_input field in the database.
	FieldTargetInput = "target_input"
	// FieldEdgeType holds the string denoting the edge_type field in the database.
	FieldEdgeType = "edge_type"
	// FieldCondition holds the string denoting the condition field in the database.
	FieldCondition = "condition"
	// EdgeWorkflow holds the string denoting the workflow edge name in mutations.
	EdgeWorkflow = "workflow"
	// EdgeSourceStep holds the string denoting the source_step edge name in mutations.
	EdgeSourceStep = "source_step"
	// EdgeTargetStep holds the string denoting the target_step edge name in mutations.
	EdgeTargetStep = "target_step"
	// Table holds the table name of the edge in the database.
	Table = "edges"
	// WorkflowTable is the table that holds the workflow relation/edge.
	WorkflowTable = "edges"
	// WorkflowInverseTable is the table name for the Workflow entity.
	// It exists in this package in order to avoid circular dependency with the "workflow" package.
	WorkflowInverseTable = "workflows"
	// WorkflowColumn is the table column denoting the workflow relation/edge.
	WorkflowColumn = "workflow_id"
	// SourceStepTable is the table that holds the source_step relation/edge.
	SourceStepTable = "edges"
	// SourceStepInverseTable is the table name for the Step entity.
	// It exists in this package in order to avoid circular dependency with the "step" package.
	SourceStepInverseTable = "steps"
	// SourceStepColumn is the table column denoting the source_step relation/edge.
	SourceStepColumn = "source_step_id"
	// TargetStepTable is the table that holds the target_step relation/edge.
	TargetStepTable = "edges"
	// TargetStepInverseTable is the table name for the Step entity.
	// It exists in this package in order to avoid circular dependency with the "step" package.
	TargetStepInverseTable = "steps"
	// TargetStepColumn is the table column denoting the target_step relation/edge.
	TargetStepColumn = "target_step_id"
)

// Columns holds all SQL columns for edge fields.
var Columns = []string{
	FieldID,
	FieldDateCreated,
	FieldDateUpdated,
	FieldWorkflowID,
	FieldSourceStepID,
	FieldTargetStepID,
	FieldSourceOutput,
	FieldTargetInput,
	FieldEdgeType,
	FieldCondition,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "react-go-workflow/ent/runtime"
var (
	Hooks [2]ent.Hook
	// DefaultDateCreated holds the default value on creation for the "date_created" field.
	DefaultDateCreated func() time.Time
	// SourceOutputValidator is a validator for the "source_output" field. It is called by the builders before save.
	SourceOutputValidator func(string) error
	// TargetInputValidator is a validator for the "target_input" field. It is called by the builders before save.
	TargetInputValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// EdgeType defines the type for the "edge_type" enum field.
type EdgeType string

// EdgeTypeNormal is the default value of the EdgeType enum.
const DefaultEdgeType = EdgeTypeNormal

// EdgeType values.
const (
	EdgeTypeNormal EdgeType = "normal"
	EdgeTypeError  EdgeType = "error"
)

func (et EdgeType) String() string {
	return string(et)
}

// EdgeTypeValidator is a validator for the "edge_type" field enum values. It is called by the builders before save.
func EdgeTypeValidator(et EdgeType) error {
	switch et {
	case EdgeTypeNormal, EdgeTypeError:
		return nil
	default:
		return fmt.Errorf("edge: invalid enum value for edge_type field: %q", et)
	}
}

// OrderOption defines the ordering options for the Edge queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDateCreated orders the results by the date_created field.
func ByDateCreated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateCreated, opts...).ToFunc()
}

// ByDateUpdated orders the results by the date_updated field.
func ByDateUpdated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateUpdated, opts...).ToFunc()
}

// ByWorkflowID orders the results by the workflow_id field.
func ByWorkflowID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkflowID, opts...).ToFunc()
}

// BySourceStepID orders the results by the source_step_id field.
func BySourceStepID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceStepID, opts...).ToFunc()
}

// ByTargetStepID orders the results by the target_step_id field.
func ByTargetStepID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetStepID, opts...).ToFunc()
}

// BySourceOutput orders the results by the source_output field.
func BySourceOutput(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceOutput, opts...).ToFunc()
}

// ByTargetInput orders the results by the target_input field.
func ByTargetInput(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetInput, opts...).ToFunc()
}

// ByEdgeType orders the results by the edge_type field.
func ByEdgeType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEdgeType, opts...).ToFunc()
}

// ByWorkflowField orders the results by workflow field.
func ByWorkflowField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newWorkflowStep(), sql.OrderByField(field, opts...))
	}
}

// BySourceStepField orders the results by source_step field.
func BySourceStepField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSourceStepStep(), sql.OrderByField(field, opts...))
	}
}

// ByTargetStepField orders the results by target_step field.
func ByTargetStepField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTargetStepStep(), sql.OrderByField(field, opts...))
	}
}
func newWorkflowStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(WorkflowInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, WorkflowTable, WorkflowColumn),
	)
}
func newSourceStepStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SourceStepInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SourceStepTable, SourceStepColumn),
	)
}
func newTargetStepStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TargetStepInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TargetStepTable, TargetStepColumn),
	)
}
