// Code generated by ent, DO NOT EDIT.

package edge

import (
	"react-go-workflow/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Edge {
	return predicate.Edge(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Edge {
	return predicate.Edge(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Edge {
	return predicate.Edge(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Edge {
	return predicate.Edge(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Edge {
	return predicate.Edge(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Edge {
	return predicate.Edge(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Edge {
	return predicate.Edge(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Edge {
	return predicate.Edge(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Edge {
	return predicate.Edge(sql.FieldLTE(FieldID, id))
}

// DateCreated applies equality check predicate on the "date_created" field. It's identical to DateCreatedEQ.
func DateCreated(v time.Time) predicate.Edge {
	return predicate.Edge(sql.FieldEQ(FieldDateCreated, v))
}

// DateUpdated applies equality check predicate on the "date_updated" field. It's identical to DateUpdatedEQ.
func DateUpdated(v time.Time) predicate.Edge {
	return predicate.Edge(sql.FieldEQ(FieldDateUpdated, v))
}

// WorkflowID applies equality check predicate on the "workflow_id" field. It's identical to WorkflowIDEQ.
func WorkflowID(v uuid.UUID) predicate.Edge {
	return predicate.Edge(sql.FieldEQ(FieldWorkflowID, v))
}

// SourceStepID applies equality check predicate on the "source_step_id" field. It's identical to SourceStepIDEQ.
func SourceStepID(v uuid.UUID) predicate.Edge {
	return predicate.Edge(sql.FieldEQ(FieldSourceStepID, v))
}

// TargetStepID applies equality check predicate on the "target_step_id" field. It's identical to TargetStepIDEQ.
func TargetStepID(v uuid.UUID) predicate.Edge {
	return predicate.Edge(sql.FieldEQ(FieldTargetStepID, v))
}

// SourceOutput applies equality check predicate on the "source_output" field. It's identical to SourceOutputEQ.
func SourceOutput(v string) predicate.Edge {
	return predicate.Edge(sql.FieldEQ(FieldSourceOutput, v))
}

// TargetInput applies equality check predicate on the "target_input" field. It's identical to TargetInputEQ.
func TargetInput(v string) predicate.Edge {
	return predicate.Edge(sql.FieldEQ(FieldTargetInput, v))
}

// DateCreatedEQ applies the EQ predicate on the "date_created" field.
func DateCreatedEQ(v time.Time) predicate.Edge {
	return predicate.Edge(sql.FieldEQ(FieldDateCreated, v))
}

// DateCreatedNEQ applies the NEQ predicate on the "date_created" field.
func DateCreatedNEQ(v time.Time) predicate.Edge {
	return predicate.Edge(sql.FieldNEQ(FieldDateCreated, v))
}

// DateCreatedIn applies the In predicate on the "date_created" field.
func DateCreatedIn(vs ...time.Time) predicate.Edge {
	return predicate.Edge(sql.FieldIn(FieldDateCreated, vs...))
}

// DateCreatedNotIn applies the NotIn predicate on the "date_created" field.
func DateCreatedNotIn(vs ...time.Time) predicate.Edge {
	return predicate.Edge(sql.FieldNotIn(FieldDateCreated, vs...))
}

// DateCreatedGT applies the GT predicate on the "date_created" field.
func DateCreatedGT(v time.Time) predicate.Edge {
	return predicate.Edge(sql.FieldGT(FieldDateCreated, v))
}

// DateCreatedGTE applies the GTE predicate on the "date_created" field.
func DateCreatedGTE(v time.Time) predicate.Edge {
	return predicate.Edge(sql.FieldGTE(FieldDateCreated, v))
}

// DateCreatedLT applies the LT predicate on the "date_created" field.
func DateCreatedLT(v time.Time) predicate.Edge {
	return predicate.Edge(sql.FieldLT(FieldDateCreated, v))
}

// DateCreatedLTE applies the LTE predicate on the "date_created" field.
func DateCreatedLTE(v time.Time) predicate.Edge {
	return predicate.Edge(sql.FieldLTE(FieldDateCreated, v))
}

// DateUpdatedEQ applies the EQ predicate on the "date_updated" field.
func DateUpdatedEQ(v time.Time) predicate.Edge {
	return predicate.Edge(sql.FieldEQ(FieldDateUpdated, v))
}

// DateUpdatedNEQ applies the NEQ predicate on the "date_updated" field.
func DateUpdatedNEQ(v time.Time) predicate.Edge {
	return predicate.Edge(sql.FieldNEQ(FieldDateUpdated, v))
}

// DateUpdatedIn applies the In predicate on the "date_updated" field.
func DateUpdatedIn(vs ...time.Time) predicate.Edge {
	return predicate.Edge(sql.FieldIn(FieldDateUpdated, vs...))
}

// DateUpdatedNotIn applies the NotIn predicate on the "date_updated" field.
func DateUpdatedNotIn(vs ...time.Time) predicate.Edge {
	return predicate.Edge(sql.FieldNotIn(FieldDateUpdated, vs...))
}

// DateUpdatedGT applies the GT predicate on the "date_updated" field.
func DateUpdatedGT(v time.Time) predicate.Edge {
	return predicate.Edge(sql.FieldGT(FieldDateUpdated, v))
}

// DateUpdatedGTE applies the GTE predicate on the "date_updated" field.
func DateUpdatedGTE(v time.Time) predicate.Edge {
	return predicate.Edge(sql.FieldGTE(FieldDateUpdated, v))
}

// DateUpdatedLT applies the LT predicate on the "date_updated" field.
func DateUpdatedLT(v time.Time) predicate.Edge {
	return predicate.Edge(sql.FieldLT(FieldDateUpdated, v))
}

// DateUpdatedLTE applies the LTE predicate on the "date_updated" field.
func DateUpdatedLTE(v time.Time) predicate.Edge {
	return predicate.Edge(sql.FieldLTE(FieldDateUpdated, v))
}

// DateUpdatedIsNil applies the IsNil predicate on the "date_updated" field.
func DateUpdatedIsNil() predicate.Edge {
	return predicate.Edge(sql.FieldIsNull(FieldDateUpdated))
}

// DateUpdatedNotNil applies the NotNil predicate on the "date_updated" field.
func DateUpdatedNotNil() predicate.Edge {
	return predicate.Edge(sql.FieldNotNull(FieldDateUpdated))
}

// WorkflowIDEQ applies the EQ predicate on the "workflow_id" field.
func WorkflowIDEQ(v uuid.UUID) predicate.Edge {
	return predicate.Edge(sql.FieldEQ(FieldWorkflowID, v))
}

// WorkflowIDNEQ applies the NEQ predicate on the "workflow_id" field.
func WorkflowIDNEQ(v uuid.UUID) predicate.Edge {
	return predicate.Edge(sql.FieldNEQ(FieldWorkflowID, v))
}

// WorkflowIDIn applies the In predicate on the "workflow_id" field.
func WorkflowIDIn(vs ...uuid.UUID) predicate.Edge {
	return predicate.Edge(sql.FieldIn(FieldWorkflowID, vs...))
}

// WorkflowIDNotIn applies the NotIn predicate on the "workflow_id" field.
func WorkflowIDNotIn(vs ...uuid.UUID) predicate.Edge {
	return predicate.Edge(sql.FieldNotIn(FieldWorkflowID, vs...))
}

// SourceStepIDEQ applies the EQ predicate on the "source_step_id" field.
func SourceStepIDEQ(v uuid.UUID) predicate.Edge {
	return predicate.Edge(sql.FieldEQ(FieldSourceStepID, v))
}

// SourceStepIDNEQ applies the NEQ predicate on the "source_step_id" field.
func SourceStepIDNEQ(v uuid.UUID) predicate.Edge {
	return predicate.Edge(sql.FieldNEQ(FieldSourceStepID, v))
}

// SourceStepIDIn applies the In predicate on the "source_step_id" field.
func SourceStepIDIn(vs ...uuid.UUID) predicate.Edge {
	return predicate.Edge(sql.FieldIn(FieldSourceStepID, vs...))
}

// SourceStepIDNotIn applies the NotIn predicate on the "source_step_id" field.
func SourceStepIDNotIn(vs ...uuid.UUID) predicate.Edge {
	return predicate.Edge(sql.FieldNotIn(FieldSourceStepID, vs...))
}

// TargetStepIDEQ applies the EQ predicate on the "target_step_id" field.
func TargetStepIDEQ(v uuid.UUID) predicate.Edge {
	return predicate.Edge(sql.FieldEQ(FieldTargetStepID, v))
}

// TargetStepIDNEQ applies the NEQ predicate on the "target_step_id" field.
func TargetStepIDNEQ(v uuid.UUID) predicate.Edge {
	return predicate.Edge(sql.FieldNEQ(FieldTargetStepID, v))
}

// TargetStepIDIn applies the In predicate on the "target_step_id" field.
func TargetStepIDIn(vs ...uuid.UUID) predicate.Edge {
	return predicate.Edge(sql.FieldIn(FieldTargetStepID, vs...))
}

// TargetStepIDNotIn applies the NotIn predicate on the "target_step_id" field.
func TargetStepIDNotIn(vs ...uuid.UUID) predicate.Edge {
	return predicate.Edge(sql.FieldNotIn(FieldTargetStepID, vs...))
}

// SourceOutputEQ applies the EQ predicate on the "source_output" field.
func SourceOutputEQ(v string) predicate.Edge {
	return predicate.Edge(sql.FieldEQ(FieldSourceOutput, v))
}

// SourceOutputNEQ applies the NEQ predicate on the "source_output" field.
func SourceOutputNEQ(v string) predicate.Edge {
	return predicate.Edge(sql.FieldNEQ(FieldSourceOutput, v))
}

// SourceOutputIn applies the In predicate on the "source_output" field.
func SourceOutputIn(vs ...string) predicate.Edge {
	return predicate.Edge(sql.FieldIn(FieldSourceOutput, vs...))
}

// SourceOutputNotIn applies the NotIn predicate on the "source_output" field.
func SourceOutputNotIn(vs ...string) predicate.Edge {
	return predicate.Edge(sql.FieldNotIn(FieldSourceOutput, vs...))
}

// SourceOutputGT applies the GT predicate on the "source_output" field.
func SourceOutputGT(v string) predicate.Edge {
	return predicate.Edge(sql.FieldGT(FieldSourceOutput, v))
}

// SourceOutputGTE applies the GTE predicate on the "source_output" field.
func SourceOutputGTE(v string) predicate.Edge {
	return predicate.Edge(sql.FieldGTE(FieldSourceOutput, v))
}

// SourceOutputLT applies the LT predicate on the "source_output" field.
func SourceOutputLT(v string) predicate.Edge {
	return predicate.Edge(sql.FieldLT(FieldSourceOutput, v))
}

// SourceOutputLTE applies the LTE predicate on the "source_output" field.
func SourceOutputLTE(v string) predicate.Edge {
	return predicate.Edge(sql.FieldLTE(FieldSourceOutput, v))
}

// SourceOutputContains applies the Contains predicate on the "source_output" field.
func SourceOutputContains(v string) predicate.Edge {
	return predicate.Edge(sql.FieldContains(FieldSourceOutput, v))
}

// SourceOutputHasPrefix applies the HasPrefix predicate on the "source_output" field.
func SourceOutputHasPrefix(v string) predicate.Edge {
	return predicate.Edge(sql.FieldHasPrefix(FieldSourceOutput, v))
}

// SourceOutputHasSuffix applies the HasSuffix predicate on the "source_output" field.
func SourceOutputHasSuffix(v string) predicate.Edge {
	return predicate.Edge(sql.FieldHasSuffix(FieldSourceOutput, v))
}

// SourceOutputIsNil applies the IsNil predicate on the "source_output" field.
func SourceOutputIsNil() predicate.Edge {
	return predicate.Edge(sql.FieldIsNull(FieldSourceOutput))
}

// SourceOutputNotNil applies the NotNil predicate on the "source_output" field.
func SourceOutputNotNil() predicate.Edge {
	return predicate.Edge(sql.FieldNotNull(FieldSourceOutput))
}

// SourceOutputEqualFold applies the EqualFold predicate on the "source_output" field.
func SourceOutputEqualFold(v string) predicate.Edge {
	return predicate.Edge(sql.FieldEqualFold(FieldSourceOutput, v))
}

// SourceOutputContainsFold applies the ContainsFold predicate on the "source_output" field.
func SourceOutputContainsFold(v string) predicate.Edge {
	return predicate.Edge(sql.FieldContainsFold(FieldSourceOutput, v))
}

// TargetInputEQ applies the EQ predicate on the "target_input" field.
func TargetInputEQ(v string) predicate.Edge {
	return predicate.Edge(sql.FieldEQ(FieldTargetInput, v))
}

// TargetInputNEQ applies the NEQ predicate on the "target_input" field.
func TargetInputNEQ(v string) predicate.Edge {
	return predicate.Edge(sql.FieldNEQ(FieldTargetInput, v))
}

// TargetInputIn applies the In predicate on the "target_input" field.
func TargetInputIn(vs ...string) predicate.Edge {
	return predicate.Edge(sql.FieldIn(FieldTargetInput, vs...))
}

// TargetInputNotIn applies the NotIn predicate on the "target_input" field.
func TargetInputNotIn(vs ...string) predicate.Edge {
	return predicate.Edge(sql.FieldNotIn(FieldTargetInput, vs...))
}

// TargetInputGT applies the GT predicate on the "target_input" field.
func TargetInputGT(v string) predicate.Edge {
	return predicate.Edge(sql.FieldGT(FieldTargetInput, v))
}

// TargetInputGTE applies the GTE predicate on the "target_input" field.
func TargetInputGTE(v string) predicate.Edge {
	return predicate.Edge(sql.FieldGTE(FieldTargetInput, v))
}

// TargetInputLT applies the LT predicate on the "target_input" field.
func TargetInputLT(v string) predicate.Edge {
	return predicate.Edge(sql.FieldLT(FieldTargetInput, v))
}

// TargetInputLTE applies the LTE predicate on the "target_input" field.
func TargetInputLTE(v string) predicate.Edge {
	return predicate.Edge(sql.FieldLTE(FieldTargetInput, v))
}

// TargetInputContains applies the Contains predicate on the "target_input" field.
func TargetInputContains(v string) predicate.Edge {
	return predicate.Edge(sql.FieldContains(FieldTargetInput, v))
}

// TargetInputHasPrefix applies the HasPrefix predicate on the "target_input" field.
func TargetInputHasPrefix(v string) predicate.Edge {
	return predicate.Edge(sql.FieldHasPrefix(FieldTargetInput, v))
}

// TargetInputHasSuffix applies the HasSuffix predicate on the "target_input" field.
func TargetInputHasSuffix(v string) predicate.Edge {
	return predicate.Edge(sql.FieldHasSuffix(FieldTargetInput, v))
}

// TargetInputIsNil applies the IsNil predicate on the "target_input" field.
func TargetInputIsNil() predicate.Edge {
	return predicate.Edge(sql.FieldIsNull(FieldTargetInput))
}

// TargetInputNotNil applies the NotNil predicate on the "target_input" field.
func TargetInputNotNil() predicate.Edge {
	return predicate.Edge(sql.FieldNotNull(FieldTargetInput))
}

// TargetInputEqualFold applies the EqualFold predicate on the "target_input" field.
func TargetInputEqualFold(v string) predicate.Edge {
	return predicate.Edge(sql.FieldEqualFold(FieldTargetInput, v))
}

// TargetInputContainsFold applies the ContainsFold predicate on the "target_input" field.
func TargetInputContainsFold(v string) predicate.Edge {
	return predicate.Edge(sql.FieldContainsFold(FieldTargetInput, v))
}

// EdgeTypeEQ applies the EQ predicate on the "edge_type" field.
func EdgeTypeEQ(v EdgeType) predicate.Edge {
	return predicate.Edge(sql.FieldEQ(FieldEdgeType, v))
}

// EdgeTypeNEQ applies the NEQ predicate on the "edge_type" field.
func EdgeTypeNEQ(v EdgeType) predicate.Edge {
	return predicate.Edge(sql.FieldNEQ(FieldEdgeType, v))
}

// EdgeTypeIn applies the In predicate on the "edge_type" field.
func EdgeTypeIn(vs ...EdgeType) predicate.Edge {
	return predicate.Edge(sql.FieldIn(FieldEdgeType, vs...))
}

// EdgeTypeNotIn applies the NotIn predicate on the "edge_type" field.
func EdgeTypeNotIn(vs ...EdgeType) predicate.Edge {
	return predicate.Edge(sql.FieldNotIn(FieldEdgeType, vs...))
}

// ConditionIsNil applies the IsNil predicate on the "condition" field.
func ConditionIsNil() predicate.Edge {
	return predicate.Edge(sql.FieldIsNull(FieldCondition))
}

// ConditionNotNil applies the NotNil predicate on the "condition" field.
func ConditionNotNil() predicate.Edge {
	return predicate.Edge(sql.FieldNotNull(FieldCondition))
}

// HasWorkflow applies the HasEdge predicate on the "workflow" edge.
func HasWorkflow() predicate.Edge {
	return predicate.Edge(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, WorkflowTable, WorkflowColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWorkflowWith applies the HasEdge predicate on the "workflow" edge with a given conditions (other predicates).
func HasWorkflowWith(preds ...predicate.Workflow) predicate.Edge {
	return predicate.Edge(func(s *sql.Selector) {
		step := newWorkflowStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSourceStep applies the HasEdge predicate on the "source_step" edge.
func HasSourceStep() predicate.Edge {
	return predicate.Edge(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SourceStepTable, SourceStepColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSourceStepWith applies the HasEdge predicate on the "source_step" edge with a given conditions (other predicates).
func HasSourceStepWith(preds ...predicate.Step) predicate.Edge {
	return predicate.Edge(func(s *sql.Selector) {
		step := newSourceStepStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTargetStep applies the HasEdge predicate on the "target_step" edge.
func HasTargetStep() predicate.Edge {
	return predicate.Edge(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TargetStepTable, TargetStepColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTargetStepWith applies the HasEdge predicate on the "target_step" edge with a given conditions (other predicates).
func HasTargetStepWith(preds ...predicate.Step) predicate.Edge {
	return predicate.Edge(func(s *sql.Selector) {
		step := newTargetStepStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Edge) predicate.Edge {
	return predicate.Edge(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Edge) predicate.Edge {
	return predicate.Edge(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Edge) predicate.Edge {
	return predicate.Edge(sql.NotPredicates(p))
}
