// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"react-go-workflow/ent/canvasnote"
	"react-go-workflow/ent/workflow"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// CanvasNote is the model entity for the CanvasNote schema.
type CanvasNote struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// DateCreated holds the value of the "date_created" field.
	DateCreated time.Time `json:"date_created,omitempty"`
	// DateUpdated holds the value of the "date_updated" field.
	DateUpdated *time.Time `json:"date_updated,omitempty"`
	// WorkflowID holds the value of the "workflow_id" field.
	WorkflowID uuid.UUID `json:"workflow_id,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// Color holds the value of the "color" field.
	Color string `json:"color,omitempty"`
	// PositionX holds the value of the "position_x" field.
	PositionX float64 `json:"position_x,omitempty"`
	// PositionY holds the value of the "position_y" field.
	PositionY float64 `json:"position_y,omitempty"`
	// Width holds the value of the "width" field.
	Width float64 `json:"width,omitempty"`
	// Height holds the value of the "height" field.
	Height float64 `json:"height,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CanvasNoteQuery when eager-loading is set.
	Edges        CanvasNoteEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CanvasNoteEdges holds the relations/edges for other nodes in the graph.
type CanvasNoteEdges struct {
	// Workflow holds the value of the workflow edge.
	Workflow *Workflow `json:"workflow,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// WorkflowOrErr returns the Workflow value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CanvasNoteEdges) WorkflowOrErr() (*Workflow, error) {
	if e.Workflow != nil {
		return e.Workflow, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: workflow.Label}
	}
	return nil, &NotLoadedError{edge: "workflow"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CanvasNote) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case canvasnote.FieldPositionX, canvasnote.FieldPositionY, canvasnote.FieldWidth, canvasnote.FieldHeight:
			values[i] = new(sql.NullFloat64)
		case canvasnote.FieldContent, canvasnote.FieldColor:
			values[i] = new(sql.NullString)
		case canvasnote.FieldDateCreated, canvasnote.FieldDateUpdated:
			values[i] = new(sql.NullTime)
		case canvasnote.FieldID, canvasnote.FieldWorkflowID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CanvasNote fields.
func (_m *CanvasNote) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case canvasnote.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case canvasnote.FieldDateCreated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_created", values[i])
			} else if value.Valid {
				_m.DateCreated = value.Time
			}
		case canvasnote.FieldDateUpdated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_updated", values[i])
			} else if value.Valid {
				_m.DateUpdated = new(time.Time)
				*_m.DateUpdated = value.Time
			}
		case canvasnote.FieldWorkflowID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field workflow_id", values[i])
			} else if value != nil {
				_m.WorkflowID = *value
			}
		case canvasnote.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case canvasnote.FieldColor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field color", values[i])
			} else if value.Valid {
				_m.Color = value.String
			}
		case canvasnote.FieldPositionX:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field position_x", values[i])
			} else if value.Valid {
				_m.PositionX = value.Float64
			}
		case canvasnote.FieldPositionY:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field position_y", values[i])
			} else if value.Valid {
				_m.PositionY = value.Float64
			}
		case canvasnote.FieldWidth:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field width", values[i])
			} else if value.Valid {
				_m.Width = value.Float64
			}
		case canvasnote.FieldHeight:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field height", values[i])
			} else if value.Valid {
				_m.Height = value.Float64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CanvasNote.
// This includes values selected through modifiers, order, etc.
func (_m *CanvasNote) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryWorkflow queries the "workflow" edge of the CanvasNote entity.
func (_m *CanvasNote) QueryWorkflow() *WorkflowQuery {
	return NewCanvasNoteClient(_m.config).QueryWorkflow(_m)
}

// Update returns a builder for updating this CanvasNote.
// Note that you need to call CanvasNote.Unwrap() before calling this method if this CanvasNote
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CanvasNote) Update() *CanvasNoteUpdateOne {
	return NewCanvasNoteClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CanvasNote entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CanvasNote) Unwrap() *CanvasNote {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CanvasNote is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CanvasNote) String() string {
	var builder strings.Builder
	builder.WriteString("CanvasNote(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("date_created=")
	builder.WriteString(_m.DateCreated.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DateUpdated; v != nil {
		builder.WriteString("date_updated=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("workflow_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.WorkflowID))
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("color=")
	builder.WriteString(_m.Color)
	builder.WriteString(", ")
	builder.WriteString("position_x=")
	builder.WriteString(fmt.Sprintf("%v", _m.PositionX))
	builder.WriteString(", ")
	builder.WriteString("position_y=")
	builder.WriteString(fmt.Sprintf("%v", _m.PositionY))
	builder.WriteString(", ")
	builder.WriteString("width=")
	builder.WriteString(fmt.Sprintf("%v", _m.Width))
	builder.WriteString(", ")
	builder.WriteString("height=")
	builder.WriteString(fmt.Sprintf("%v", _m.Height))
	builder.WriteByte(')')
	return builder.String()
}

// CanvasNotes is a parsable slice of CanvasNote.
type CanvasNotes []*CanvasNote
