// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"react-go-workflow/ent/canvasnote"
	"react-go-workflow/ent/predicate"
	"react-go-workflow/ent/workflow"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// CanvasNoteUpdate is the builder for updating CanvasNote entities.
type CanvasNoteUpdate struct {
	config
	hooks    []Hook
	mutation *CanvasNoteMutation
}

// Where appends a list predicates to the CanvasNoteUpdate builder.
func (_u *CanvasNoteUpdate) Where(ps ...predicate.CanvasNote) *CanvasNoteUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDateUpdated sets the "date_updated" field.
func (_u *CanvasNoteUpdate) SetDateUpdated(v time.Time) *CanvasNoteUpdate {
	_u.mutation.SetDateUpdated(v)
	return _u
}

// SetNillableDateUpdated sets the "date_updated" field if the given value is not nil.
func (_u *CanvasNoteUpdate) SetNillableDateUpdated(v *time.Time) *CanvasNoteUpdate {
	if v != nil {
		_u.SetDateUpdated(*v)
	}
	return _u
}

// ClearDateUpdated clears the value of the "date_updated" field.
func (_u *CanvasNoteUpdate) ClearDateUpdated() *CanvasNoteUpdate {
	_u.mutation.ClearDateUpdated()
	return _u
}

// SetWorkflowID sets the "workflow_id" field.
func (_u *CanvasNoteUpdate) SetWorkflowID(v uuid.UUID) *CanvasNoteUpdate {
	_u.mutation.SetWorkflowID(v)
	return _u
}

// SetNillableWorkflowID sets the "workflow_id" field if the given value is not nil.
func (_u *CanvasNoteUpdate) SetNillableWorkflowID(v *uuid.UUID) *CanvasNoteUpdate {
	if v != nil {
		_u.SetWorkflowID(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *CanvasNoteUpdate) SetContent(v string) *CanvasNoteUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *CanvasNoteUpdate) SetNillableContent(v *string) *CanvasNoteUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *CanvasNoteUpdate) ClearContent() *CanvasNoteUpdate {
	_u.mutation.ClearContent()
	return _u
}

// SetColor sets the "color" field.
func (_u *CanvasNoteUpdate) SetColor(v string) *CanvasNoteUpdate {
	_u.mutation.SetColor(v)
	return _u
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (_u *CanvasNoteUpdate) SetNillableColor(v *string) *CanvasNoteUpdate {
	if v != nil {
		_u.SetColor(*v)
	}
	return _u
}

// SetPositionX sets the "position_x" field.
func (_u *CanvasNoteUpdate) SetPositionX(v float64) *CanvasNoteUpdate {
	_u.mutation.ResetPositionX()
	_u.mutation.SetPositionX(v)
	return _u
}

// SetNillablePositionX sets the "position_x" field if the given value is not nil.
func (_u *CanvasNoteUpdate) SetNillablePositionX(v *float64) *CanvasNoteUpdate {
	if v != nil {
		_u.SetPositionX(*v)
	}
	return _u
}

// AddPositionX adds value to the "position_x" field.
func (_u *CanvasNoteUpdate) AddPositionX(v float64) *CanvasNoteUpdate {
	_u.mutation.AddPositionX(v)
	return _u
}

// SetPositionY sets the "position_y" field.
func (_u *CanvasNoteUpdate) SetPositionY(v float64) *CanvasNoteUpdate {
	_u.mutation.ResetPositionY()
	_u.mutation.SetPositionY(v)
	return _u
}

// SetNillablePositionY sets the "position_y" field if the given value is not nil.
func (_u *CanvasNoteUpdate) SetNillablePositionY(v *float64) *CanvasNoteUpdate {
	if v != nil {
		_u.SetPositionY(*v)
	}
	return _u
}

// AddPositionY adds value to the "position_y" field.
func (_u *CanvasNoteUpdate) AddPositionY(v float64) *CanvasNoteUpdate {
	_u.mutation.AddPositionY(v)
	return _u
}

// SetWidth sets the "width" field.
func (_u *CanvasNoteUpdate) SetWidth(v float64) *CanvasNoteUpdate {
	_u.mutation.ResetWidth()
	_u.mutation.SetWidth(v)
	return _u
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_u *CanvasNoteUpdate) SetNillableWidth(v *float64) *CanvasNoteUpdate {
	if v != nil {
		_u.SetWidth(*v)
	}
	return _u
}

// AddWidth adds value to the "width" field.
func (_u *CanvasNoteUpdate) AddWidth(v float64) *CanvasNoteUpdate {
	_u.mutation.AddWidth(v)
	return _u
}

// SetHeight sets the "height" field.
func (_u *CanvasNoteUpdate) SetHeight(v float64) *CanvasNoteUpdate {
	_u.mutation.ResetHeight()
	_u.mutation.SetHeight(v)
	return _u
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_u *CanvasNoteUpdate) SetNillableHeight(v *float64) *CanvasNoteUpdate {
	if v != nil {
		_u.SetHeight(*v)
	}
	return _u
}

// AddHeight adds value to the "height" field.
func (_u *CanvasNoteUpdate) AddHeight(v float64) *CanvasNoteUpdate {
	_u.mutation.AddHeight(v)
	return _u
}

// SetWorkflow sets the "workflow" edge to the Workflow entity.
func (_u *CanvasNoteUpdate) SetWorkflow(v *Workflow) *CanvasNoteUpdate {
	return _u.SetWorkflowID(v.ID)
}

// Mutation returns the CanvasNoteMutation object of the builder.
func (_u *CanvasNoteUpdate) Mutation() *CanvasNoteMutation {
	return _u.mutation
}

// ClearWorkflow clears the "workflow" edge to the Workflow entity.
func (_u *CanvasNoteUpdate) ClearWorkflow() *CanvasNoteUpdate {
	_u.mutation.ClearWorkflow()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CanvasNoteUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CanvasNoteUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CanvasNoteUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CanvasNoteUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CanvasNoteUpdate) check() error {
	if v, ok := _u.mutation.Content(); ok {
		if err := canvasnote.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "CanvasNote.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Color(); ok {
		if err := canvasnote.ColorValidator(v); err != nil {
			return &ValidationError{Name: "color", err: fmt.Errorf(`ent: validator failed for field "CanvasNote.color": %w`, err)}
		}
	}
	if _u.mutation.WorkflowCleared() && len(_u.mutation.WorkflowIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CanvasNote.workflow"`)
	}
	return nil
}

func (_u *CanvasNoteUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(canvasnote.Table, canvasnote.Columns, sqlgraph.NewFieldSpec(canvasnote.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DateUpdated(); ok {
		_spec.SetField(canvasnote.FieldDateUpdated, field.TypeTime, value)
	}
	if _u.mutation.DateUpdatedCleared() {
		_spec.ClearField(canvasnote.FieldDateUpdated, field.TypeTime)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(canvasnote.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(canvasnote.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.Color(); ok {
		_spec.SetField(canvasnote.FieldColor, field.TypeString, value)
	}
	if value, ok := _u.mutation.PositionX(); ok {
		_spec.SetField(canvasnote.FieldPositionX, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPositionX(); ok {
		_spec.AddField(canvasnote.FieldPositionX, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PositionY(); ok {
		_spec.SetField(canvasnote.FieldPositionY, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPositionY(); ok {
		_spec.AddField(canvasnote.FieldPositionY, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Width(); ok {
		_spec.SetField(canvasnote.FieldWidth, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWidth(); ok {
		_spec.AddField(canvasnote.FieldWidth, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Height(); ok {
		_spec.SetField(canvasnote.FieldHeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedHeight(); ok {
		_spec.AddField(canvasnote.FieldHeight, field.TypeFloat64, value)
	}
	if _u.mutation.WorkflowCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   canvasnote.WorkflowTable,
			Columns: []string{canvasnote.WorkflowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkflowIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   canvasnote.WorkflowTable,
			Columns: []string{canvasnote.WorkflowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{canvasnote.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CanvasNoteUpdateOne is the builder for updating a single CanvasNote entity.
type CanvasNoteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CanvasNoteMutation
}

// SetDateUpdated sets the "date_updated" field.
func (_u *CanvasNoteUpdateOne) SetDateUpdated(v time.Time) *CanvasNoteUpdateOne {
	_u.mutation.SetDateUpdated(v)
	return _u
}

// SetNillableDateUpdated sets the "date_updated" field if the given value is not nil.
func (_u *CanvasNoteUpdateOne) SetNillableDateUpdated(v *time.Time) *CanvasNoteUpdateOne {
	if v != nil {
		_u.SetDateUpdated(*v)
	}
	return _u
}

// ClearDateUpdated clears the value of the "date_updated" field.
func (_u *CanvasNoteUpdateOne) ClearDateUpdated() *CanvasNoteUpdateOne {
	_u.mutation.ClearDateUpdated()
	return _u
}

// SetWorkflowID sets the "workflow_id" field.
func (_u *CanvasNoteUpdateOne) SetWorkflowID(v uuid.UUID) *CanvasNoteUpdateOne {
	_u.mutation.SetWorkflowID(v)
	return _u
}

// SetNillableWorkflowID sets the "workflow_id" field if the given value is not nil.
func (_u *CanvasNoteUpdateOne) SetNillableWorkflowID(v *uuid.UUID) *CanvasNoteUpdateOne {
	if v != nil {
		_u.SetWorkflowID(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *CanvasNoteUpdateOne) SetContent(v string) *CanvasNoteUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *CanvasNoteUpdateOne) SetNillableContent(v *string) *CanvasNoteUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *CanvasNoteUpdateOne) ClearContent() *CanvasNoteUpdateOne {
	_u.mutation.ClearContent()
	return _u
}

// SetColor sets the "color" field.
func (_u *CanvasNoteUpdateOne) SetColor(v string) *CanvasNoteUpdateOne {
	_u.mutation.SetColor(v)
	return _u
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (_u *CanvasNoteUpdateOne) SetNillableColor(v *string) *CanvasNoteUpdateOne {
	if v != nil {
		_u.SetColor(*v)
	}
	return _u
}

// SetPositionX sets the "position_x" field.
func (_u *CanvasNoteUpdateOne) SetPositionX(v float64) *CanvasNoteUpdateOne {
	_u.mutation.ResetPositionX()
	_u.mutation.SetPositionX(v)
	return _u
}

// SetNillablePositionX sets the "position_x" field if the given value is not nil.
func (_u *CanvasNoteUpdateOne) SetNillablePositionX(v *float64) *CanvasNoteUpdateOne {
	if v != nil {
		_u.SetPositionX(*v)
	}
	return _u
}

// AddPositionX adds value to the "position_x" field.
func (_u *CanvasNoteUpdateOne) AddPositionX(v float64) *CanvasNoteUpdateOne {
	_u.mutation.AddPositionX(v)
	return _u
}

// SetPositionY sets the "position_y" field.
func (_u *CanvasNoteUpdateOne) SetPositionY(v float64) *CanvasNoteUpdateOne {
	_u.mutation.ResetPositionY()
	_u.mutation.SetPositionY(v)
	return _u
}

// SetNillablePositionY sets the "position_y" field if the given value is not nil.
func (_u *CanvasNoteUpdateOne) SetNillablePositionY(v *float64) *CanvasNoteUpdateOne {
	if v != nil {
		_u.SetPositionY(*v)
	}
	return _u
}

// AddPositionY adds value to the "position_y" field.
func (_u *CanvasNoteUpdateOne) AddPositionY(v float64) *CanvasNoteUpdateOne {
	_u.mutation.AddPositionY(v)
	return _u
}

// SetWidth sets the "width" field.
func (_u *CanvasNoteUpdateOne) SetWidth(v float64) *CanvasNoteUpdateOne {
	_u.mutation.ResetWidth()
	_u.mutation.SetWidth(v)
	return _u
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_u *CanvasNoteUpdateOne) SetNillableWidth(v *float64) *CanvasNoteUpdateOne {
	if v != nil {
		_u.SetWidth(*v)
	}
	return _u
}

// AddWidth adds value to the "width" field.
func (_u *CanvasNoteUpdateOne) AddWidth(v float64) *CanvasNoteUpdateOne {
	_u.mutation.AddWidth(v)
	return _u
}

// SetHeight sets the "height" field.
func (_u *CanvasNoteUpdateOne) SetHeight(v float64) *CanvasNoteUpdateOne {
	_u.mutation.ResetHeight()
	_u.mutation.SetHeight(v)
	return _u
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_u *CanvasNoteUpdateOne) SetNillableHeight(v *float64) *CanvasNoteUpdateOne {
	if v != nil {
		_u.SetHeight(*v)
	}
	return _u
}

// AddHeight adds value to the "height" field.
func (_u *CanvasNoteUpdateOne) AddHeight(v float64) *CanvasNoteUpdateOne {
	_u.mutation.AddHeight(v)
	return _u
}

// SetWorkflow sets the "workflow" edge to the Workflow entity.
func (_u *CanvasNoteUpdateOne) SetWorkflow(v *Workflow) *CanvasNoteUpdateOne {
	return _u.SetWorkflowID(v.ID)
}

// Mutation returns the CanvasNoteMutation object of the builder.
func (_u *CanvasNoteUpdateOne) Mutation() *CanvasNoteMutation {
	return _u.mutation
}

// ClearWorkflow clears the "workflow" edge to the Workflow entity.
func (_u *CanvasNoteUpdateOne) ClearWorkflow() *CanvasNoteUpdateOne {
	_u.mutation.ClearWorkflow()
	return _u
}

// Where appends a list predicates to the CanvasNoteUpdate builder.
func (_u *CanvasNoteUpdateOne) Where(ps ...predicate.CanvasNote) *CanvasNoteUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CanvasNoteUpdateOne) Select(field string, fields ...string) *CanvasNoteUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CanvasNote entity.
func (_u *CanvasNoteUpdateOne) Save(ctx context.Context) (*CanvasNote, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CanvasNoteUpdateOne) SaveX(ctx context.Context) *CanvasNote {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CanvasNoteUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CanvasNoteUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CanvasNoteUpdateOne) check() error {
	if v, ok := _u.mutation.Content(); ok {
		if err := canvasnote.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "CanvasNote.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Color(); ok {
		if err := canvasnote.ColorValidator(v); err != nil {
			return &ValidationError{Name: "color", err: fmt.Errorf(`ent: validator failed for field "CanvasNote.color": %w`, err)}
		}
	}
	if _u.mutation.WorkflowCleared() && len(_u.mutation.WorkflowIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CanvasNote.workflow"`)
	}
	return nil
}

func (_u *CanvasNoteUpdateOne) sqlSave(ctx context.Context) (_node *CanvasNote, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(canvasnote.Table, canvasnote.Columns, sqlgraph.NewFieldSpec(canvasnote.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CanvasNote.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, canvasnote.FieldID)
		for _, f := range fields {
			if !canvasnote.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != canvasnote.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DateUpdated(); ok {
		_spec.SetField(canvasnote.FieldDateUpdated, field.TypeTime, value)
	}
	if _u.mutation.DateUpdatedCleared() {
		_spec.ClearField(canvasnote.FieldDateUpdated, field.TypeTime)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(canvasnote.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(canvasnote.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.Color(); ok {
		_spec.SetField(canvasnote.FieldColor, field.TypeString, value)
	}
	if value, ok := _u.mutation.PositionX(); ok {
		_spec.SetField(canvasnote.FieldPositionX, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPositionX(); ok {
		_spec.AddField(canvasnote.FieldPositionX, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PositionY(); ok {
		_spec.SetField(canvasnote.FieldPositionY, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPositionY(); ok {
		_spec.AddField(canvasnote.FieldPositionY, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Width(); ok {
		_spec.SetField(canvasnote.FieldWidth, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWidth(); ok {
		_spec.AddField(canvasnote.FieldWidth, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Height(); ok {
		_spec.SetField(canvasnote.FieldHeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedHeight(); ok {
		_spec.AddField(canvasnote.FieldHeight, field.TypeFloat64, value)
	}
	if _u.mutation.WorkflowCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   canvasnote.WorkflowTable,
			Columns: []string{canvasnote.WorkflowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkflowIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   canvasnote.WorkflowTable,
			Columns: []string{canvasnote.WorkflowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CanvasNote{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{canvasnote.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
