// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"react-go-workflow/ent/edge"
	"react-go-workflow/ent/step"
	"react-go-workflow/ent/workflow"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Edge is the model entity for the Edge schema.
type Edge struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// DateCreated holds the value of the "date_created" field.
	DateCreated time.Time `json:"date_created,omitempty"`
	// DateUpdated holds the value of the "date_updated" field.
	DateUpdated *time.Time `json:"date_updated,omitempty"`
	// WorkflowID holds the value of the "workflow_id" field.
	WorkflowID uuid.UUID `json:"workflow_id,omitempty"`
	// SourceStepID holds the value of the "source_step_id" field.
	SourceStepID uuid.UUID `json:"source_step_id,omitempty"`
	// TargetStepID holds the value of the "target_step_id" field.
	TargetStepID uuid.UUID `json:"target_step_id,omitempty"`
	// SourceOutput holds the value of the "source_output" field.
	SourceOutput string `json:"source_output,omitempty"`
	// TargetInput holds the value of the "target_input" field.
	TargetInput string `json:"target_input,omitempty"`
	// EdgeType holds the value of the "edge_type" field.
	EdgeType edge.EdgeType `json:"edge_type,omitempty"`
	// Condition holds the value of the "condition" field.
	Condition map[string]interface{} `json:"condition,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EdgeQuery when eager-loading is set.
	Edges        EdgeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// EdgeEdges holds the relations/edges for other nodes in the graph.
type EdgeEdges struct {
	// Workflow holds the value of the workflow edge.
	Workflow *Workflow `json:"workflow,omitempty"`
	// SourceStep holds the value of the source_step edge.
	SourceStep *Step `json:"source_step,omitempty"`
	// TargetStep holds the value of the target_step edge.
	TargetStep *Step `json:"target_step,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// WorkflowOrErr returns the Workflow value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EdgeEdges) WorkflowOrErr() (*Workflow, error) {
	if e.Workflow != nil {
		return e.Workflow, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: workflow.Label}
	}
	return nil, &NotLoadedError{edge: "workflow"}
}

// SourceStepOrErr returns the SourceStep value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EdgeEdges) SourceStepOrErr() (*Step, error) {
	if e.SourceStep != nil {
		return e.SourceStep, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: step.Label}
	}
	return nil, &NotLoadedError{edge: "source_step"}
}

// TargetStepOrErr returns the TargetStep value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EdgeEdges) TargetStepOrErr() (*Step, error) {
	if e.TargetStep != nil {
		return e.TargetStep, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: step.Label}
	}
	return nil, &NotLoadedError{edge: "target_step"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Edge) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case edge.FieldCondition:
			values[i] = new([]byte)
		case edge.FieldSourceOutput, edge.FieldTargetInput, edge.FieldEdgeType:
			values[i] = new(sql.NullString)
		case edge.FieldDateCreated, edge.FieldDateUpdated:
			values[i] = new(sql.NullTime)
		case edge.FieldID, edge.FieldWorkflowID, edge.FieldSourceStepID, edge.FieldTargetStepID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Edge fields.
func (_m *Edge) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case edge.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case edge.FieldDateCreated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_created", values[i])
			} else if value.Valid {
				_m.DateCreated = value.Time
			}
		case edge.FieldDateUpdated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_updated", values[i])
			} else if value.Valid {
				_m.DateUpdated = new(time.Time)
				*_m.DateUpdated = value.Time
			}
		case edge.FieldWorkflowID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field workflow_id", values[i])
			} else if value != nil {
				_m.WorkflowID = *value
			}
		case edge.FieldSourceStepID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field source_step_id", values[i])
			} else if value != nil {
				_m.SourceStepID = *value
			}
		case edge.FieldTargetStepID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field target_step_id", values[i])
			} else if value != nil {
				_m.TargetStepID = *value
			}
		case edge.FieldSourceOutput:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_output", values[i])
			} else if value.Valid {
				_m.SourceOutput = value.String
			}
		case edge.FieldTargetInput:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_input", values[i])
			} else if value.Valid {
				_m.TargetInput = value.String
			}
		case edge.FieldEdgeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field edge_type", values[i])
			} else if value.Valid {
				_m.EdgeType = edge.EdgeType(value.String)
			}
		case edge.FieldCondition:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field condition", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Condition); err != nil {
					return fmt.Errorf("unmarshal field condition: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Edge.
// This includes values selected through modifiers, order, etc.
func (_m *Edge) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryWorkflow queries the "workflow" edge of the Edge entity.
func (_m *Edge) QueryWorkflow() *WorkflowQuery {
	return NewEdgeClient(_m.config).QueryWorkflow(_m)
}

// QuerySourceStep queries the "source_step" edge of the Edge entity.
func (_m *Edge) QuerySourceStep() *StepQuery {
	return NewEdgeClient(_m.config).QuerySourceStep(_m)
}

// QueryTargetStep queries the "target_step" edge of the Edge entity.
func (_m *Edge) QueryTargetStep() *StepQuery {
	return NewEdgeClient(_m.config).QueryTargetStep(_m)
}

// Update returns a builder for updating this Edge.
// Note that you need to call Edge.Unwrap() before calling this method if this Edge
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Edge) Update() *EdgeUpdateOne {
	return NewEdgeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Edge entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Edge) Unwrap() *Edge {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Edge is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Edge) String() string {
	var builder strings.Builder
	builder.WriteString("Edge(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("date_created=")
	builder.WriteString(_m.DateCreated.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DateUpdated; v != nil {
		builder.WriteString("date_updated=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("workflow_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.WorkflowID))
	builder.WriteString(", ")
	builder.WriteString("source_step_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SourceStepID))
	builder.WriteString(", ")
	builder.WriteString("target_step_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TargetStepID))
	builder.WriteString(", ")
	builder.WriteString("source_output=")
	builder.WriteString(_m.SourceOutput)
	builder.WriteString(", ")
	builder.WriteString("target_input=")
	builder.WriteString(_m.TargetInput)
	builder.WriteString(", ")
	builder.WriteString("edge_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.EdgeType))
	builder.WriteString(", ")
	builder.WriteString("condition=")
	builder.WriteString(fmt.Sprintf("%v", _m.Condition))
	builder.WriteByte(')')
	return builder.String()
}

// Edges is a parsable slice of Edge.
type Edges []*Edge
