// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"react-go-workflow/ent/edge"
	"react-go-workflow/ent/predicate"
	"react-go-workflow/ent/step"
	"react-go-workflow/ent/workflow"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// EdgeUpdate is the builder for updating Edge entities.
type EdgeUpdate struct {
	config
	hooks    []Hook
	mutation *EdgeMutation
}

// Where appends a list predicates to the EdgeUpdate builder.
func (_u *EdgeUpdate) Where(ps ...predicate.Edge) *EdgeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDateUpdated sets the "date_updated" field.
func (_u *EdgeUpdate) SetDateUpdated(v time.Time) *EdgeUpdate {
	_u.mutation.SetDateUpdated(v)
	return _u
}

// SetNillableDateUpdated sets the "date_updated" field if the given value is not nil.
func (_u *EdgeUpdate) SetNillableDateUpdated(v *time.Time) *EdgeUpdate {
	if v != nil {
		_u.SetDateUpdated(*v)
	}
	return _u
}

// ClearDateUpdated clears the value of the "date_updated" field.
func (_u *EdgeUpdate) ClearDateUpdated() *EdgeUpdate {
	_u.mutation.ClearDateUpdated()
	return _u
}

// SetWorkflowID sets the "workflow_id" field.
func (_u *EdgeUpdate) SetWorkflowID(v uuid.UUID) *EdgeUpdate {
	_u.mutation.SetWorkflowID(v)
	return _u
}

// SetNillableWorkflowID sets the "workflow_id" field if the given value is not nil.
func (_u *EdgeUpdate) SetNillableWorkflowID(v *uuid.UUID) *EdgeUpdate {
	if v != nil {
		_u.SetWorkflowID(*v)
	}
	return _u
}

// SetSourceStepID sets the "source_step_id" field.
func (_u *EdgeUpdate) SetSourceStepID(v uuid.UUID) *EdgeUpdate {
	_u.mutation.SetSourceStepID(v)
	return _u
}

// SetNillableSourceStepID sets the "source_step_id" field if the given value is not nil.
func (_u *EdgeUpdate) SetNillableSourceStepID(v *uuid.UUID) *EdgeUpdate {
	if v != nil {
		_u.SetSourceStepID(*v)
	}
	return _u
}

// SetTargetStepID sets the "target_step_id" field.
func (_u *EdgeUpdate) SetTargetStepID(v uuid.UUID) *EdgeUpdate {
	_u.mutation.SetTargetStepID(v)
	return _u
}

// SetNillableTargetStepID sets the "target_step_id" field if the given value is not nil.
func (_u *EdgeUpdate) SetNillableTargetStepID(v *uuid.UUID) *EdgeUpdate {
	if v != nil {
		_u.SetTargetStepID(*v)
	}
	return _u
}

// SetSourceOutput sets the "source_output" field.
func (_u *EdgeUpdate) SetSourceOutput(v string) *EdgeUpdate {
	_u.mutation.SetSourceOutput(v)
	return _u
}

// SetNillableSourceOutput sets the "source_output" field if the given value is not nil.
func (_u *EdgeUpdate) SetNillableSourceOutput(v *string) *EdgeUpdate {
	if v != nil {
		_u.SetSourceOutput(*v)
	}
	return _u
}

// ClearSourceOutput clears the value of the "source_output" field.
func (_u *EdgeUpdate) ClearSourceOutput() *EdgeUpdate {
	_u.mutation.ClearSourceOutput()
	return _u
}

// SetTargetInput sets the "target_input" field.
func (_u *EdgeUpdate) SetTargetInput(v string) *EdgeUpdate {
	_u.mutation.SetTargetInput(v)
	return _u
}

// SetNillableTargetInput sets the "target_input" field if the given value is not nil.
func (_u *EdgeUpdate) SetNillableTargetInput(v *string) *EdgeUpdate {
	if v != nil {
		_u.SetTargetInput(*v)
	}
	return _u
}

// ClearTargetInput clears the value of the "target_input" field.
func (_u *EdgeUpdate) ClearTargetInput() *EdgeUpdate {
	_u.mutation.ClearTargetInput()
	return _u
}

// SetEdgeType sets the "edge_type" field.
func (_u *EdgeUpdate) SetEdgeType(v edge.EdgeType) *EdgeUpdate {
	_u.mutation.SetEdgeType(v)
	return _u
}

// SetNillableEdgeType sets the "edge_type" field if the given value is not nil.
func (_u *EdgeUpdate) SetNillableEdgeType(v *edge.EdgeType) *EdgeUpdate {
	if v != nil {
		_u.SetEdgeType(*v)
	}
	return _u
}

// SetCondition sets the "condition" field.
func (_u *EdgeUpdate) SetCondition(v map[string]interface{}) *EdgeUpdate {
	_u.mutation.SetCondition(v)
	return _u
}

// ClearCondition clears the value of the "condition" field.
func (_u *EdgeUpdate) ClearCondition() *EdgeUpdate {
	_u.mutation.ClearCondition()
	return _u
}

// SetWorkflow sets the "workflow" edge to the Workflow entity.
func (_u *EdgeUpdate) SetWorkflow(v *Workflow) *EdgeUpdate {
	return _u.SetWorkflowID(v.ID)
}

// SetSourceStep sets the "source_step" edge to the Step entity.
func (_u *EdgeUpdate) SetSourceStep(v *Step) *EdgeUpdate {
	return _u.SetSourceStepID(v.ID)
}

// SetTargetStep sets the "target_step" edge to the Step entity.
func (_u *EdgeUpdate) SetTargetStep(v *Step) *EdgeUpdate {
	return _u.SetTargetStepID(v.ID)
}

// Mutation returns the EdgeMutation object of the builder.
func (_u *EdgeUpdate) Mutation() *EdgeMutation {
	return _u.mutation
}

// ClearWorkflow clears the "workflow" edge to the Workflow entity.
func (_u *EdgeUpdate) ClearWorkflow() *EdgeUpdate {
	_u.mutation.ClearWorkflow()
	return _u
}

// ClearSourceStep clears the "source_step" edge to the Step entity.
func (_u *EdgeUpdate) ClearSourceStep() *EdgeUpdate {
	_u.mutation.ClearSourceStep()
	return _u
}

// ClearTargetStep clears the "target_step" edge to the Step entity.
func (_u *EdgeUpdate) ClearTargetStep() *EdgeUpdate {
	_u.mutation.ClearTargetStep()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EdgeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EdgeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EdgeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EdgeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EdgeUpdate) check() error {
	if v, ok := _u.mutation.SourceOutput(); ok {
		if err := edge.SourceOutputValidator(v); err != nil {
			return &ValidationError{Name: "source_output", err: fmt.Errorf(`ent: validator failed for field "Edge.source_output": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetInput(); ok {
		if err := edge.TargetInputValidator(v); err != nil {
			return &ValidationError{Name: "target_input", err: fmt.Errorf(`ent: validator failed for field "Edge.target_input": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EdgeType(); ok {
		if err := edge.EdgeTypeValidator(v); err != nil {
			return &ValidationError{Name: "edge_type", err: fmt.Errorf(`ent: validator failed for field "Edge.edge_type": %w`, err)}
		}
	}
	if _u.mutation.WorkflowCleared() && len(_u.mutation.WorkflowIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Edge.workflow"`)
	}
	if _u.mutation.SourceStepCleared() && len(_u.mutation.SourceStepIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Edge.source_step"`)
	}
	if _u.mutation.TargetStepCleared() && len(_u.mutation.TargetStepIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Edge.target_step"`)
	}
	return nil
}

func (_u *EdgeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(edge.Table, edge.Columns, sqlgraph.NewFieldSpec(edge.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DateUpdated(); ok {
		_spec.SetField(edge.FieldDateUpdated, field.TypeTime, value)
	}
	if _u.mutation.DateUpdatedCleared() {
		_spec.ClearField(edge.FieldDateUpdated, field.TypeTime)
	}
	if value, ok := _u.mutation.SourceOutput(); ok {
		_spec.SetField(edge.FieldSourceOutput, field.TypeString, value)
	}
	if _u.mutation.SourceOutputCleared() {
		_spec.ClearField(edge.FieldSourceOutput, field.TypeString)
	}
	if value, ok := _u.mutation.TargetInput(); ok {
		_spec.SetField(edge.FieldTargetInput, field.TypeString, value)
	}
	if _u.mutation.TargetInputCleared() {
		_spec.ClearField(edge.FieldTargetInput, field.TypeString)
	}
	if value, ok := _u.mutation.EdgeType(); ok {
		_spec.SetField(edge.FieldEdgeType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Condition(); ok {
		_spec.SetField(edge.FieldCondition, field.TypeJSON, value)
	}
	if _u.mutation.ConditionCleared() {
		_spec.ClearField(edge.FieldCondition, field.TypeJSON)
	}
	if _u.mutation.WorkflowCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   edge.WorkflowTable,
			Columns: []string{edge.WorkflowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkflowIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   edge.WorkflowTable,
			Columns: []string{edge.WorkflowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SourceStepCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   edge.SourceStepTable,
			Columns: []string{edge.SourceStepColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(step.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceStepIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   edge.SourceStepTable,
			Columns: []string{edge.SourceStepColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(step.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TargetStepCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   edge.TargetStepTable,
			Columns: []string{edge.TargetStepColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(step.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TargetStepIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   edge.TargetStepTable,
			Columns: []string{edge.TargetStepColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(step.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{edge.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EdgeUpdateOne is the builder for updating a single Edge entity.
type EdgeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EdgeMutation
}

// SetDateUpdated sets the "date_updated" field.
func (_u *EdgeUpdateOne) SetDateUpdated(v time.Time) *EdgeUpdateOne {
	_u.mutation.SetDateUpdated(v)
	return _u
}

// SetNillableDateUpdated sets the "date_updated" field if the given value is not nil.
func (_u *EdgeUpdateOne) SetNillableDateUpdated(v *time.Time) *EdgeUpdateOne {
	if v != nil {
		_u.SetDateUpdated(*v)
	}
	return _u
}

// ClearDateUpdated clears the value of the "date_updated" field.
func (_u *EdgeUpdateOne) ClearDateUpdated() *EdgeUpdateOne {
	_u.mutation.ClearDateUpdated()
	return _u
}

// SetWorkflowID sets the "workflow_id" field.
func (_u *EdgeUpdateOne) SetWorkflowID(v uuid.UUID) *EdgeUpdateOne {
	_u.mutation.SetWorkflowID(v)
	return _u
}

// SetNillableWorkflowID sets the "workflow_id" field if the given value is not nil.
func (_u *EdgeUpdateOne) SetNillableWorkflowID(v *uuid.UUID) *EdgeUpdateOne {
	if v != nil {
		_u.SetWorkflowID(*v)
	}
	return _u
}

// SetSourceStepID sets the "source_step_id" field.
func (_u *EdgeUpdateOne) SetSourceStepID(v uuid.UUID) *EdgeUpdateOne {
	_u.mutation.SetSourceStepID(v)
	return _u
}

// SetNillableSourceStepID sets the "source_step_id" field if the given value is not nil.
func (_u *EdgeUpdateOne) SetNillableSourceStepID(v *uuid.UUID) *EdgeUpdateOne {
	if v != nil {
		_u.SetSourceStepID(*v)
	}
	return _u
}

// SetTargetStepID sets the "target_step_id" field.
func (_u *EdgeUpdateOne) SetTargetStepID(v uuid.UUID) *EdgeUpdateOne {
	_u.mutation.SetTargetStepID(v)
	return _u
}

// SetNillableTargetStepID sets the "target_step_id" field if the given value is not nil.
func (_u *EdgeUpdateOne) SetNillableTargetStepID(v *uuid.UUID) *EdgeUpdateOne {
	if v != nil {
		_u.SetTargetStepID(*v)
	}
	return _u
}

// SetSourceOutput sets the "source_output" field.
func (_u *EdgeUpdateOne) SetSourceOutput(v string) *EdgeUpdateOne {
	_u.mutation.SetSourceOutput(v)
	return _u
}

// SetNillableSourceOutput sets the "source_output" field if the given value is not nil.
func (_u *EdgeUpdateOne) SetNillableSourceOutput(v *string) *EdgeUpdateOne {
	if v != nil {
		_u.SetSourceOutput(*v)
	}
	return _u
}

// ClearSourceOutput clears the value of the "source_output" field.
func (_u *EdgeUpdateOne) ClearSourceOutput() *EdgeUpdateOne {
	_u.mutation.ClearSourceOutput()
	return _u
}

// SetTargetInput sets the "target_input" field.
func (_u *EdgeUpdateOne) SetTargetInput(v string) *EdgeUpdateOne {
	_u.mutation.SetTargetInput(v)
	return _u
}

// SetNillableTargetInput sets the "target_input" field if the given value is not nil.
func (_u *EdgeUpdateOne) SetNillableTargetInput(v *string) *EdgeUpdateOne {
	if v != nil {
		_u.SetTargetInput(*v)
	}
	return _u
}

// ClearTargetInput clears the value of the "target_input" field.
func (_u *EdgeUpdateOne) ClearTargetInput() *EdgeUpdateOne {
	_u.mutation.ClearTargetInput()
	return _u
}

// SetEdgeType sets the "edge_type" field.
func (_u *EdgeUpdateOne) SetEdgeType(v edge.EdgeType) *EdgeUpdateOne {
	_u.mutation.SetEdgeType(v)
	return _u
}

// SetNillableEdgeType sets the "edge_type" field if the given value is not nil.
func (_u *EdgeUpdateOne) SetNillableEdgeType(v *edge.EdgeType) *EdgeUpdateOne {
	if v != nil {
		_u.SetEdgeType(*v)
	}
	return _u
}

// SetCondition sets the "condition" field.
func (_u *EdgeUpdateOne) SetCondition(v map[string]interface{}) *EdgeUpdateOne {
	_u.mutation.SetCondition(v)
	return _u
}

// ClearCondition clears the value of the "condition" field.
func (_u *EdgeUpdateOne) ClearCondition() *EdgeUpdateOne {
	_u.mutation.ClearCondition()
	return _u
}

// SetWorkflow sets the "workflow" edge to the Workflow entity.
func (_u *EdgeUpdateOne) SetWorkflow(v *Workflow) *EdgeUpdateOne {
	return _u.SetWorkflowID(v.ID)
}

// SetSourceStep sets the "source_step" edge to the Step entity.
func (_u *EdgeUpdateOne) SetSourceStep(v *Step) *EdgeUpdateOne {
	return _u.SetSourceStepID(v.ID)
}

// SetTargetStep sets the "target_step" edge to the Step entity.
func (_u *EdgeUpdateOne) SetTargetStep(v *Step) *EdgeUpdateOne {
	return _u.SetTargetStepID(v.ID)
}

// Mutation returns the EdgeMutation object of the builder.
func (_u *EdgeUpdateOne) Mutation() *EdgeMutation {
	return _u.mutation
}

// ClearWorkflow clears the "workflow" edge to the Workflow entity.
func (_u *EdgeUpdateOne) ClearWorkflow() *EdgeUpdateOne {
	_u.mutation.ClearWorkflow()
	return _u
}

// ClearSourceStep clears the "source_step" edge to the Step entity.
func (_u *EdgeUpdateOne) ClearSourceStep() *EdgeUpdateOne {
	_u.mutation.ClearSourceStep()
	return _u
}

// ClearTargetStep clears the "target_step" edge to the Step entity.
func (_u *EdgeUpdateOne) ClearTargetStep() *EdgeUpdateOne {
	_u.mutation.ClearTargetStep()
	return _u
}

// Where appends a list predicates to the EdgeUpdate builder.
func (_u *EdgeUpdateOne) Where(ps ...predicate.Edge) *EdgeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EdgeUpdateOne) Select(field string, fields ...string) *EdgeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Edge entity.
func (_u *EdgeUpdateOne) Save(ctx context.Context) (*Edge, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EdgeUpdateOne) SaveX(ctx context.Context) *Edge {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EdgeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EdgeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EdgeUpdateOne) check() error {
	if v, ok := _u.mutation.SourceOutput(); ok {
		if err := edge.SourceOutputValidator(v); err != nil {
			return &ValidationError{Name: "source_output", err: fmt.Errorf(`ent: validator failed for field "Edge.source_output": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetInput(); ok {
		if err := edge.TargetInputValidator(v); err != nil {
			return &ValidationError{Name: "target_input", err: fmt.Errorf(`ent: validator failed for field "Edge.target_input": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EdgeType(); ok {
		if err := edge.EdgeTypeValidator(v); err != nil {
			return &ValidationError{Name: "edge_type", err: fmt.Errorf(`ent: validator failed for field "Edge.edge_type": %w`, err)}
		}
	}
	if _u.mutation.WorkflowCleared() && len(_u.mutation.WorkflowIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Edge.workflow"`)
	}
	if _u.mutation.SourceStepCleared() && len(_u.mutation.SourceStepIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Edge.source_step"`)
	}
	if _u.mutation.TargetStepCleared() && len(_u.mutation.TargetStepIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Edge.target_step"`)
	}
	return nil
}

func (_u *EdgeUpdateOne) sqlSave(ctx context.Context) (_node *Edge, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(edge.Table, edge.Columns, sqlgraph.NewFieldSpec(edge.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Edge.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, edge.FieldID)
		for _, f := range fields {
			if !edge.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != edge.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DateUpdated(); ok {
		_spec.SetField(edge.FieldDateUpdated, field.TypeTime, value)
	}
	if _u.mutation.DateUpdatedCleared() {
		_spec.ClearField(edge.FieldDateUpdated, field.TypeTime)
	}
	if value, ok := _u.mutation.SourceOutput(); ok {
		_spec.SetField(edge.FieldSourceOutput, field.TypeString, value)
	}
	if _u.mutation.SourceOutputCleared() {
		_spec.ClearField(edge.FieldSourceOutput, field.TypeString)
	}
	if value, ok := _u.mutation.TargetInput(); ok {
		_spec.SetField(edge.FieldTargetInput, field.TypeString, value)
	}
	if _u.mutation.TargetInputCleared() {
		_spec.ClearField(edge.FieldTargetInput, field.TypeString)
	}
	if value, ok := _u.mutation.EdgeType(); ok {
		_spec.SetField(edge.FieldEdgeType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Condition(); ok {
		_spec.SetField(edge.FieldCondition, field.TypeJSON, value)
	}
	if _u.mutation.ConditionCleared() {
		_spec.ClearField(edge.FieldCondition, field.TypeJSON)
	}
	if _u.mutation.WorkflowCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   edge.WorkflowTable,
			Columns: []string{edge.WorkflowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkflowIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   edge.WorkflowTable,
			Columns: []string{edge.WorkflowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SourceStepCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   edge.SourceStepTable,
			Columns: []string{edge.SourceStepColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(step.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceStepIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   edge.SourceStepTable,
			Columns: []string{edge.SourceStepColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(step.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TargetStepCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   edge.TargetStepTable,
			Columns: []string{edge.TargetStepColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(step.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TargetStepIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   edge.TargetStepTable,
			Columns: []string{edge.TargetStepColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(step.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Edge{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{edge.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
