// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"react-go-workflow/ent/notification"
	"react-go-workflow/ent/workflow"
	"react-go-workflow/ent/workflowexecution"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// NotificationCreate is the builder for creating a Notification entity.
type NotificationCreate struct {
	config
	mutation *NotificationMutation
	hooks    []Hook
}

// SetDateCreated sets the "date_created" field.
func (_c *NotificationCreate) SetDateCreated(v time.Time) *NotificationCreate {
	_c.mutation.SetDateCreated(v)
	return _c
}

// SetNillableDateCreated sets the "date_created" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableDateCreated(v *time.Time) *NotificationCreate {
	if v != nil {
		_c.SetDateCreated(*v)
	}
	return _c
}

// SetDateUpdated sets the "date_updated" field.
func (_c *NotificationCreate) SetDateUpdated(v time.Time) *NotificationCreate {
	_c.mutation.SetDateUpdated(v)
	return _c
}

// SetNillableDateUpdated sets the "date_updated" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableDateUpdated(v *time.Time) *NotificationCreate {
	if v != nil {
		_c.SetDateUpdated(*v)
	}
	return _c
}

// SetWorkflowExecutionID sets the "workflow_execution_id" field.
func (_c *NotificationCreate) SetWorkflowExecutionID(v uuid.UUID) *NotificationCreate {
	_c.mutation.SetWorkflowExecutionID(v)
	return _c
}

// SetWorkflowID sets the "workflow_id" field.
func (_c *NotificationCreate) SetWorkflowID(v uuid.UUID) *NotificationCreate {
	_c.mutation.SetWorkflowID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *NotificationCreate) SetTitle(v string) *NotificationCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetMessage sets the "message" field.
func (_c *NotificationCreate) SetMessage(v string) *NotificationCreate {
	_c.mutation.SetMessage(v)
	return _c
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableMessage(v *string) *NotificationCreate {
	if v != nil {
		_c.SetMessage(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *NotificationCreate) SetStatus(v notification.Status) *NotificationCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableStatus(v *notification.Status) *NotificationCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSeverity sets the "severity" field.
func (_c *NotificationCreate) SetSeverity(v notification.Severity) *NotificationCreate {
	_c.mutation.SetSeverity(v)
	return _c
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableSeverity(v *notification.Severity) *NotificationCreate {
	if v != nil {
		_c.SetSeverity(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *NotificationCreate) SetID(v uuid.UUID) *NotificationCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableID(v *uuid.UUID) *NotificationCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetWorkflow sets the "workflow" edge to the Workflow entity.
func (_c *NotificationCreate) SetWorkflow(v *Workflow) *NotificationCreate {
	return _c.SetWorkflowID(v.ID)
}

// SetWorkflowExecution sets the "workflow_execution" edge to the WorkflowExecution entity.
func (_c *NotificationCreate) SetWorkflowExecution(v *WorkflowExecution) *NotificationCreate {
	return _c.SetWorkflowExecutionID(v.ID)
}

// Mutation returns the NotificationMutation object of the builder.
func (_c *NotificationCreate) Mutation() *NotificationMutation {
	return _c.mutation
}

// Save creates the Notification in the database.
func (_c *NotificationCreate) Save(ctx context.Context) (*Notification, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NotificationCreate) SaveX(ctx context.Context) *Notification {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NotificationCreate) defaults() error {
	if _, ok := _c.mutation.DateCreated(); !ok {
		if notification.DefaultDateCreated == nil {
			return fmt.Errorf("ent: uninitialized notification.DefaultDateCreated (forgotten import ent/runtime?)")
		}
		v := notification.DefaultDateCreated()
		_c.mutation.SetDateCreated(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := notification.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Severity(); !ok {
		v := notification.DefaultSeverity
		_c.mutation.SetSeverity(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		if notification.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized notification.DefaultID (forgotten import ent/runtime?)")
		}
		v := notification.DefaultID()
		_c.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *NotificationCreate) check() error {
	if _, ok := _c.mutation.DateCreated(); !ok {
		return &ValidationError{Name: "date_created", err: errors.New(`ent: missing required field "Notification.date_created"`)}
	}
	if _, ok := _c.mutation.WorkflowExecutionID(); !ok {
		return &ValidationError{Name: "workflow_execution_id", err: errors.New(`ent: missing required field "Notification.workflow_execution_id"`)}
	}
	if _, ok := _c.mutation.WorkflowID(); !ok {
		return &ValidationError{Name: "workflow_id", err: errors.New(`ent: missing required field "Notification.workflow_id"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Notification.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := notification.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Notification.title": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Message(); ok {
		if err := notification.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "Notification.message": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Notification.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := notification.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Notification.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Severity(); !ok {
		return &ValidationError{Name: "severity", err: errors.New(`ent: missing required field "Notification.severity"`)}
	}
	if v, ok := _c.mutation.Severity(); ok {
		if err := notification.SeverityValidator(v); err != nil {
			return &ValidationError{Name: "severity", err: fmt.Errorf(`ent: validator failed for field "Notification.severity": %w`, err)}
		}
	}
	if len(_c.mutation.WorkflowIDs()) == 0 {
		return &ValidationError{Name: "workflow", err: errors.New(`ent: missing required edge "Notification.workflow"`)}
	}
	if len(_c.mutation.WorkflowExecutionIDs()) == 0 {
		return &ValidationError{Name: "workflow_execution", err: errors.New(`ent: missing required edge "Notification.workflow_execution"`)}
	}
	return nil
}

func (_c *NotificationCreate) sqlSave(ctx context.Context) (*Notification, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NotificationCreate) createSpec() (*Notification, *sqlgraph.CreateSpec) {
	var (
		_node = &Notification{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(notification.Table, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.DateCreated(); ok {
		_spec.SetField(notification.FieldDateCreated, field.TypeTime, value)
		_node.DateCreated = value
	}
	if value, ok := _c.mutation.DateUpdated(); ok {
		_spec.SetField(notification.FieldDateUpdated, field.TypeTime, value)
		_node.DateUpdated = &value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(notification.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Message(); ok {
		_spec.SetField(notification.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(notification.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Severity(); ok {
		_spec.SetField(notification.FieldSeverity, field.TypeEnum, value)
		_node.Severity = value
	}
	if nodes := _c.mutation.WorkflowIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notification.WorkflowTable,
			Columns: []string{notification.WorkflowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.WorkflowID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.WorkflowExecutionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notification.WorkflowExecutionTable,
			Columns: []string{notification.WorkflowExecutionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflowexecution.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.WorkflowExecutionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// NotificationCreateBulk is the builder for creating many Notification entities in bulk.
type NotificationCreateBulk struct {
	config
	err      error
	builders []*NotificationCreate
}

// Save creates the Notification entities in the database.
func (_c *NotificationCreateBulk) Save(ctx context.Context) ([]*Notification, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Notification, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NotificationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NotificationCreateBulk) SaveX(ctx context.Context) []*Notification {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
