// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"react-go-workflow/ent/notificationsetting"
	"react-go-workflow/ent/predicate"
	"react-go-workflow/ent/workflow"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// NotificationSettingQuery is the builder for querying NotificationSetting entities.
type NotificationSettingQuery struct {
	config
	ctx          *QueryContext
	order        []notificationsetting.OrderOption
	inters       []Interceptor
	predicates   []predicate.NotificationSetting
	withWorkflow *WorkflowQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the NotificationSettingQuery builder.
func (_q *NotificationSettingQuery) Where(ps ...predicate.NotificationSetting) *NotificationSettingQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *NotificationSettingQuery) Limit(limit int) *NotificationSettingQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *NotificationSettingQuery) Offset(offset int) *NotificationSettingQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *NotificationSettingQuery) Unique(unique bool) *NotificationSettingQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *NotificationSettingQuery) Order(o ...notificationsetting.OrderOption) *NotificationSettingQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryWorkflow chains the current query on the "workflow" edge.
func (_q *NotificationSettingQuery) QueryWorkflow() *WorkflowQuery {
	query := (&WorkflowClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(notificationsetting.Table, notificationsetting.FieldID, selector),
			sqlgraph.To(workflow.Table, workflow.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, notificationsetting.WorkflowTable, notificationsetting.WorkflowColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first NotificationSetting entity from the query.
// Returns a *NotFoundError when no NotificationSetting was found.
func (_q *NotificationSettingQuery) First(ctx context.Context) (*NotificationSetting, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{notificationsetting.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *NotificationSettingQuery) FirstX(ctx context.Context) *NotificationSetting {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first NotificationSetting ID from the query.
// Returns a *NotFoundError when no NotificationSetting ID was found.
func (_q *NotificationSettingQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{notificationsetting.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *NotificationSettingQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single NotificationSetting entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one NotificationSetting entity is found.
// Returns a *NotFoundError when no NotificationSetting entities are found.
func (_q *NotificationSettingQuery) Only(ctx context.Context) (*NotificationSetting, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{notificationsetting.Label}
	default:
		return nil, &NotSingularError{notificationsetting.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *NotificationSettingQuery) OnlyX(ctx context.Context) *NotificationSetting {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only NotificationSetting ID in the query.
// Returns a *NotSingularError when more than one NotificationSetting ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *NotificationSettingQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{notificationsetting.Label}
	default:
		err = &NotSingularError{notificationsetting.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *NotificationSettingQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of NotificationSettings.
func (_q *NotificationSettingQuery) All(ctx context.Context) ([]*NotificationSetting, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*NotificationSetting, *NotificationSettingQuery]()
	return withInterceptors[[]*NotificationSetting](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *NotificationSettingQuery) AllX(ctx context.Context) []*NotificationSetting {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of NotificationSetting IDs.
func (_q *NotificationSettingQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(notificationsetting.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *NotificationSettingQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *NotificationSettingQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*NotificationSettingQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *NotificationSettingQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *NotificationSettingQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *NotificationSettingQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the NotificationSettingQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *NotificationSettingQuery) Clone() *NotificationSettingQuery {
	if _q == nil {
		return nil
	}
	return &NotificationSettingQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]notificationsetting.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.NotificationSetting{}, _q.predicates...),
		withWorkflow: _q.withWorkflow.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithWorkflow tells the query-builder to eager-load the nodes that are connected to
// the "workflow" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *NotificationSettingQuery) WithWorkflow(opts ...func(*WorkflowQuery)) *NotificationSettingQuery {
	query := (&WorkflowClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withWorkflow = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		DateCreated time.Time `json:"date_created,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.NotificationSetting.Query().
//		GroupBy(notificationsetting.FieldDateCreated).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *NotificationSettingQuery) GroupBy(field string, fields ...string) *NotificationSettingGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &NotificationSettingGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = notificationsetting.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		DateCreated time.Time `json:"date_created,omitempty"`
//	}
//
//	client.NotificationSetting.Query().
//		Select(notificationsetting.FieldDateCreated).
//		Scan(ctx, &v)
func (_q *NotificationSettingQuery) Select(fields ...string) *NotificationSettingSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &NotificationSettingSelect{NotificationSettingQuery: _q}
	sbuild.label = notificationsetting.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a NotificationSettingSelect configured with the given aggregations.
func (_q *NotificationSettingQuery) Aggregate(fns ...AggregateFunc) *NotificationSettingSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *NotificationSettingQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !notificationsetting.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *NotificationSettingQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*NotificationSetting, error) {
	var (
		nodes       = []*NotificationSetting{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withWorkflow != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*NotificationSetting).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &NotificationSetting{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withWorkflow; query != nil {
		if err := _q.loadWorkflow(ctx, query, nodes, nil,
			func(n *NotificationSetting, e *Workflow) { n.Edges.Workflow = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *NotificationSettingQuery) loadWorkflow(ctx context.Context, query *WorkflowQuery, nodes []*NotificationSetting, init func(*NotificationSetting), assign func(*NotificationSetting, *Workflow)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*NotificationSetting)
	for i := range nodes {
		fk := nodes[i].WorkflowID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(workflow.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "workflow_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *NotificationSettingQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *NotificationSettingQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(notificationsetting.Table, notificationsetting.Columns, sqlgraph.NewFieldSpec(notificationsetting.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notificationsetting.FieldID)
		for i := range fields {
			if fields[i] != notificationsetting.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withWorkflow != nil {
			_spec.Node.AddColumnOnce(notificationsetting.FieldWorkflowID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *NotificationSettingQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(notificationsetting.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = notificationsetting.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// NotificationSettingGroupBy is the group-by builder for NotificationSetting entities.
type NotificationSettingGroupBy struct {
	selector
	build *NotificationSettingQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *NotificationSettingGroupBy) Aggregate(fns ...AggregateFunc) *NotificationSettingGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *NotificationSettingGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NotificationSettingQuery, *NotificationSettingGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *NotificationSettingGroupBy) sqlScan(ctx context.Context, root *NotificationSettingQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// NotificationSettingSelect is the builder for selecting fields of NotificationSetting entities.
type NotificationSettingSelect struct {
	*NotificationSettingQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *NotificationSettingSelect) Aggregate(fns ...AggregateFunc) *NotificationSettingSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *NotificationSettingSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NotificationSettingQuery, *NotificationSettingSelect](ctx, _s.NotificationSettingQuery, _s, _s.inters, v)
}

func (_s *NotificationSettingSelect) sqlScan(ctx context.Context, root *NotificationSettingQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
