// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"react-go-workflow/ent/notificationsetting"
	"react-go-workflow/ent/workflow"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// NotificationSetting is the model entity for the NotificationSetting schema.
type NotificationSetting struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// DateCreated holds the value of the "date_created" field.
	DateCreated time.Time `json:"date_created,omitempty"`
	// DateUpdated holds the value of the "date_updated" field.
	DateUpdated *time.Time `json:"date_updated,omitempty"`
	// WorkflowID holds the value of the "workflow_id" field.
	WorkflowID uuid.UUID `json:"workflow_id,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// Channel holds the value of the "channel" field.
	Channel notificationsetting.Channel `json:"channel,omitempty"`
	// Config holds the value of the "config" field.
	Config map[string]interface{} `json:"config,omitempty"`
	// NotifyOn holds the value of the "notify_on" field.
	NotifyOn notificationsetting.NotifyOn `json:"notify_on,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the NotificationSettingQuery when eager-loading is set.
	Edges        NotificationSettingEdges `json:"edges"`
	selectValues sql.SelectValues
}

// NotificationSettingEdges holds the relations/edges for other nodes in the graph.
type NotificationSettingEdges struct {
	// Workflow holds the value of the workflow edge.
	Workflow *Workflow `json:"workflow,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// WorkflowOrErr returns the Workflow value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NotificationSettingEdges) WorkflowOrErr() (*Workflow, error) {
	if e.Workflow != nil {
		return e.Workflow, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: workflow.Label}
	}
	return nil, &NotLoadedError{edge: "workflow"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*NotificationSetting) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case notificationsetting.FieldConfig:
			values[i] = new([]byte)
		case notificationsetting.FieldEnabled:
			values[i] = new(sql.NullBool)
		case notificationsetting.FieldChannel, notificationsetting.FieldNotifyOn:
			values[i] = new(sql.NullString)
		case notificationsetting.FieldDateCreated, notificationsetting.FieldDateUpdated:
			values[i] = new(sql.NullTime)
		case notificationsetting.FieldID, notificationsetting.FieldWorkflowID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the NotificationSetting fields.
func (_m *NotificationSetting) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case notificationsetting.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case notificationsetting.FieldDateCreated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_created", values[i])
			} else if value.Valid {
				_m.DateCreated = value.Time
			}
		case notificationsetting.FieldDateUpdated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_updated", values[i])
			} else if value.Valid {
				_m.DateUpdated = new(time.Time)
				*_m.DateUpdated = value.Time
			}
		case notificationsetting.FieldWorkflowID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field workflow_id", values[i])
			} else if value != nil {
				_m.WorkflowID = *value
			}
		case notificationsetting.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case notificationsetting.FieldChannel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channel", values[i])
			} else if value.Valid {
				_m.Channel = notificationsetting.Channel(value.String)
			}
		case notificationsetting.FieldConfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field config", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Config); err != nil {
					return fmt.Errorf("unmarshal field config: %w", err)
				}
			}
		case notificationsetting.FieldNotifyOn:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notify_on", values[i])
			} else if value.Valid {
				_m.NotifyOn = notificationsetting.NotifyOn(value.String)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the NotificationSetting.
// This includes values selected through modifiers, order, etc.
func (_m *NotificationSetting) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryWorkflow queries the "workflow" edge of the NotificationSetting entity.
func (_m *NotificationSetting) QueryWorkflow() *WorkflowQuery {
	return NewNotificationSettingClient(_m.config).QueryWorkflow(_m)
}

// Update returns a builder for updating this NotificationSetting.
// Note that you need to call NotificationSetting.Unwrap() before calling this method if this NotificationSetting
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *NotificationSetting) Update() *NotificationSettingUpdateOne {
	return NewNotificationSettingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the NotificationSetting entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *NotificationSetting) Unwrap() *NotificationSetting {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: NotificationSetting is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *NotificationSetting) String() string {
	var builder strings.Builder
	builder.WriteString("NotificationSetting(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("date_created=")
	builder.WriteString(_m.DateCreated.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DateUpdated; v != nil {
		builder.WriteString("date_updated=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("workflow_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.WorkflowID))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("channel=")
	builder.WriteString(fmt.Sprintf("%v", _m.Channel))
	builder.WriteString(", ")
	builder.WriteString("config=")
	builder.WriteString(fmt.Sprintf("%v", _m.Config))
	builder.WriteString(", ")
	builder.WriteString("notify_on=")
	builder.WriteString(fmt.Sprintf("%v", _m.NotifyOn))
	builder.WriteByte(')')
	return builder.String()
}

// NotificationSettings is a parsable slice of NotificationSetting.
type NotificationSettings []*NotificationSetting
