// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"react-go-workflow/ent/notificationsetting"
	"react-go-workflow/ent/workflow"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// NotificationSettingCreate is the builder for creating a NotificationSetting entity.
type NotificationSettingCreate struct {
	config
	mutation *NotificationSettingMutation
	hooks    []Hook
}

// SetDateCreated sets the "date_created" field.
func (_c *NotificationSettingCreate) SetDateCreated(v time.Time) *NotificationSettingCreate {
	_c.mutation.SetDateCreated(v)
	return _c
}

// SetNillableDateCreated sets the "date_created" field if the given value is not nil.
func (_c *NotificationSettingCreate) SetNillableDateCreated(v *time.Time) *NotificationSettingCreate {
	if v != nil {
		_c.SetDateCreated(*v)
	}
	return _c
}

// SetDateUpdated sets the "date_updated" field.
func (_c *NotificationSettingCreate) SetDateUpdated(v time.Time) *NotificationSettingCreate {
	_c.mutation.SetDateUpdated(v)
	return _c
}

// SetNillableDateUpdated sets the "date_updated" field if the given value is not nil.
func (_c *NotificationSettingCreate) SetNillableDateUpdated(v *time.Time) *NotificationSettingCreate {
	if v != nil {
		_c.SetDateUpdated(*v)
	}
	return _c
}

// SetWorkflowID sets the "workflow_id" field.
func (_c *NotificationSettingCreate) SetWorkflowID(v uuid.UUID) *NotificationSettingCreate {
	_c.mutation.SetWorkflowID(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *NotificationSettingCreate) SetEnabled(v bool) *NotificationSettingCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *NotificationSettingCreate) SetNillableEnabled(v *bool) *NotificationSettingCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetChannel sets the "channel" field.
func (_c *NotificationSettingCreate) SetChannel(v notificationsetting.Channel) *NotificationSettingCreate {
	_c.mutation.SetChannel(v)
	return _c
}

// SetConfig sets the "config" field.
func (_c *NotificationSettingCreate) SetConfig(v map[string]interface{}) *NotificationSettingCreate {
	_c.mutation.SetConfig(v)
	return _c
}

// SetNotifyOn sets the "notify_on" field.
func (_c *NotificationSettingCreate) SetNotifyOn(v notificationsetting.NotifyOn) *NotificationSettingCreate {
	_c.mutation.SetNotifyOn(v)
	return _c
}

// SetNillableNotifyOn sets the "notify_on" field if the given value is not nil.
func (_c *NotificationSettingCreate) SetNillableNotifyOn(v *notificationsetting.NotifyOn) *NotificationSettingCreate {
	if v != nil {
		_c.SetNotifyOn(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *NotificationSettingCreate) SetID(v uuid.UUID) *NotificationSettingCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *NotificationSettingCreate) SetNillableID(v *uuid.UUID) *NotificationSettingCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetWorkflow sets the "workflow" edge to the Workflow entity.
func (_c *NotificationSettingCreate) SetWorkflow(v *Workflow) *NotificationSettingCreate {
	return _c.SetWorkflowID(v.ID)
}

// Mutation returns the NotificationSettingMutation object of the builder.
func (_c *NotificationSettingCreate) Mutation() *NotificationSettingMutation {
	return _c.mutation
}

// Save creates the NotificationSetting in the database.
func (_c *NotificationSettingCreate) Save(ctx context.Context) (*NotificationSetting, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NotificationSettingCreate) SaveX(ctx context.Context) *NotificationSetting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationSettingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationSettingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NotificationSettingCreate) defaults() error {
	if _, ok := _c.mutation.DateCreated(); !ok {
		if notificationsetting.DefaultDateCreated == nil {
			return fmt.Errorf("ent: uninitialized notificationsetting.DefaultDateCreated (forgotten import ent/runtime?)")
		}
		v := notificationsetting.DefaultDateCreated()
		_c.mutation.SetDateCreated(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := notificationsetting.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.NotifyOn(); !ok {
		v := notificationsetting.DefaultNotifyOn
		_c.mutation.SetNotifyOn(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		if notificationsetting.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized notificationsetting.DefaultID (forgotten import ent/runtime?)")
		}
		v := notificationsetting.DefaultID()
		_c.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *NotificationSettingCreate) check() error {
	if _, ok := _c.mutation.DateCreated(); !ok {
		return &ValidationError{Name: "date_created", err: errors.New(`ent: missing required field "NotificationSetting.date_created"`)}
	}
	if _, ok := _c.mutation.WorkflowID(); !ok {
		return &ValidationError{Name: "workflow_id", err: errors.New(`ent: missing required field "NotificationSetting.workflow_id"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "NotificationSetting.enabled"`)}
	}
	if _, ok := _c.mutation.Channel(); !ok {
		return &ValidationError{Name: "channel", err: errors.New(`ent: missing required field "NotificationSetting.channel"`)}
	}
	if v, ok := _c.mutation.Channel(); ok {
		if err := notificationsetting.ChannelValidator(v); err != nil {
			return &ValidationError{Name: "channel", err: fmt.Errorf(`ent: validator failed for field "NotificationSetting.channel": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NotifyOn(); !ok {
		return &ValidationError{Name: "notify_on", err: errors.New(`ent: missing required field "NotificationSetting.notify_on"`)}
	}
	if v, ok := _c.mutation.NotifyOn(); ok {
		if err := notificationsetting.NotifyOnValidator(v); err != nil {
			return &ValidationError{Name: "notify_on", err: fmt.Errorf(`ent: validator failed for field "NotificationSetting.notify_on": %w`, err)}
		}
	}
	if len(_c.mutation.WorkflowIDs()) == 0 {
		return &ValidationError{Name: "workflow", err: errors.New(`ent: missing required edge "NotificationSetting.workflow"`)}
	}
	return nil
}

func (_c *NotificationSettingCreate) sqlSave(ctx context.Context) (*NotificationSetting, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NotificationSettingCreate) createSpec() (*NotificationSetting, *sqlgraph.CreateSpec) {
	var (
		_node = &NotificationSetting{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(notificationsetting.Table, sqlgraph.NewFieldSpec(notificationsetting.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.DateCreated(); ok {
		_spec.SetField(notificationsetting.FieldDateCreated, field.TypeTime, value)
		_node.DateCreated = value
	}
	if value, ok := _c.mutation.DateUpdated(); ok {
		_spec.SetField(notificationsetting.FieldDateUpdated, field.TypeTime, value)
		_node.DateUpdated = &value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(notificationsetting.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Channel(); ok {
		_spec.SetField(notificationsetting.FieldChannel, field.TypeEnum, value)
		_node.Channel = value
	}
	if value, ok := _c.mutation.Config(); ok {
		_spec.SetField(notificationsetting.FieldConfig, field.TypeJSON, value)
		_node.Config = value
	}
	if value, ok := _c.mutation.NotifyOn(); ok {
		_spec.SetField(notificationsetting.FieldNotifyOn, field.TypeEnum, value)
		_node.NotifyOn = value
	}
	if nodes := _c.mutation.WorkflowIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notificationsetting.WorkflowTable,
			Columns: []string{notificationsetting.WorkflowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.WorkflowID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// NotificationSettingCreateBulk is the builder for creating many NotificationSetting entities in bulk.
type NotificationSettingCreateBulk struct {
	config
	err      error
	builders []*NotificationSettingCreate
}

// Save creates the NotificationSetting entities in the database.
func (_c *NotificationSettingCreateBulk) Save(ctx context.Context) ([]*NotificationSetting, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NotificationSetting, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NotificationSettingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NotificationSettingCreateBulk) SaveX(ctx context.Context) []*NotificationSetting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationSettingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationSettingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
