// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"react-go-workflow/ent/notification"
	"react-go-workflow/ent/predicate"
	"react-go-workflow/ent/workflow"
	"react-go-workflow/ent/workflowexecution"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// NotificationUpdate is the builder for updating Notification entities.
type NotificationUpdate struct {
	config
	hooks    []Hook
	mutation *NotificationMutation
}

// Where appends a list predicates to the NotificationUpdate builder.
func (_u *NotificationUpdate) Where(ps ...predicate.Notification) *NotificationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDateUpdated sets the "date_updated" field.
func (_u *NotificationUpdate) SetDateUpdated(v time.Time) *NotificationUpdate {
	_u.mutation.SetDateUpdated(v)
	return _u
}

// SetNillableDateUpdated sets the "date_updated" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableDateUpdated(v *time.Time) *NotificationUpdate {
	if v != nil {
		_u.SetDateUpdated(*v)
	}
	return _u
}

// ClearDateUpdated clears the value of the "date_updated" field.
func (_u *NotificationUpdate) ClearDateUpdated() *NotificationUpdate {
	_u.mutation.ClearDateUpdated()
	return _u
}

// SetWorkflowExecutionID sets the "workflow_execution_id" field.
func (_u *NotificationUpdate) SetWorkflowExecutionID(v uuid.UUID) *NotificationUpdate {
	_u.mutation.SetWorkflowExecutionID(v)
	return _u
}

// SetNillableWorkflowExecutionID sets the "workflow_execution_id" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableWorkflowExecutionID(v *uuid.UUID) *NotificationUpdate {
	if v != nil {
		_u.SetWorkflowExecutionID(*v)
	}
	return _u
}

// SetWorkflowID sets the "workflow_id" field.
func (_u *NotificationUpdate) SetWorkflowID(v uuid.UUID) *NotificationUpdate {
	_u.mutation.SetWorkflowID(v)
	return _u
}

// SetNillableWorkflowID sets the "workflow_id" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableWorkflowID(v *uuid.UUID) *NotificationUpdate {
	if v != nil {
		_u.SetWorkflowID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *NotificationUpdate) SetTitle(v string) *NotificationUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableTitle(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *NotificationUpdate) SetMessage(v string) *NotificationUpdate {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableMessage(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// ClearMessage clears the value of the "message" field.
func (_u *NotificationUpdate) ClearMessage() *NotificationUpdate {
	_u.mutation.ClearMessage()
	return _u
}

// SetStatus sets the "status" field.
func (_u *NotificationUpdate) SetStatus(v notification.Status) *NotificationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableStatus(v *notification.Status) *NotificationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSeverity sets the "severity" field.
func (_u *NotificationUpdate) SetSeverity(v notification.Severity) *NotificationUpdate {
	_u.mutation.SetSeverity(v)
	return _u
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableSeverity(v *notification.Severity) *NotificationUpdate {
	if v != nil {
		_u.SetSeverity(*v)
	}
	return _u
}

// SetWorkflow sets the "workflow" edge to the Workflow entity.
func (_u *NotificationUpdate) SetWorkflow(v *Workflow) *NotificationUpdate {
	return _u.SetWorkflowID(v.ID)
}

// SetWorkflowExecution sets the "workflow_execution" edge to the WorkflowExecution entity.
func (_u *NotificationUpdate) SetWorkflowExecution(v *WorkflowExecution) *NotificationUpdate {
	return _u.SetWorkflowExecutionID(v.ID)
}

// Mutation returns the NotificationMutation object of the builder.
func (_u *NotificationUpdate) Mutation() *NotificationMutation {
	return _u.mutation
}

// ClearWorkflow clears the "workflow" edge to the Workflow entity.
func (_u *NotificationUpdate) ClearWorkflow() *NotificationUpdate {
	_u.mutation.ClearWorkflow()
	return _u
}

// ClearWorkflowExecution clears the "workflow_execution" edge to the WorkflowExecution entity.
func (_u *NotificationUpdate) ClearWorkflowExecution() *NotificationUpdate {
	_u.mutation.ClearWorkflowExecution()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NotificationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NotificationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := notification.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Notification.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Message(); ok {
		if err := notification.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "Notification.message": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := notification.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Notification.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Severity(); ok {
		if err := notification.SeverityValidator(v); err != nil {
			return &ValidationError{Name: "severity", err: fmt.Errorf(`ent: validator failed for field "Notification.severity": %w`, err)}
		}
	}
	if _u.mutation.WorkflowCleared() && len(_u.mutation.WorkflowIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Notification.workflow"`)
	}
	if _u.mutation.WorkflowExecutionCleared() && len(_u.mutation.WorkflowExecutionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Notification.workflow_execution"`)
	}
	return nil
}

func (_u *NotificationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notification.Table, notification.Columns, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DateUpdated(); ok {
		_spec.SetField(notification.FieldDateUpdated, field.TypeTime, value)
	}
	if _u.mutation.DateUpdatedCleared() {
		_spec.ClearField(notification.FieldDateUpdated, field.TypeTime)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(notification.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(notification.FieldMessage, field.TypeString, value)
	}
	if _u.mutation.MessageCleared() {
		_spec.ClearField(notification.FieldMessage, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(notification.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Severity(); ok {
		_spec.SetField(notification.FieldSeverity, field.TypeEnum, value)
	}
	if _u.mutation.WorkflowCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notification.WorkflowTable,
			Columns: []string{notification.WorkflowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkflowIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notification.WorkflowTable,
			Columns: []string{notification.WorkflowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WorkflowExecutionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notification.WorkflowExecutionTable,
			Columns: []string{notification.WorkflowExecutionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflowexecution.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkflowExecutionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notification.WorkflowExecutionTable,
			Columns: []string{notification.WorkflowExecutionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflowexecution.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NotificationUpdateOne is the builder for updating a single Notification entity.
type NotificationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NotificationMutation
}

// SetDateUpdated sets the "date_updated" field.
func (_u *NotificationUpdateOne) SetDateUpdated(v time.Time) *NotificationUpdateOne {
	_u.mutation.SetDateUpdated(v)
	return _u
}

// SetNillableDateUpdated sets the "date_updated" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableDateUpdated(v *time.Time) *NotificationUpdateOne {
	if v != nil {
		_u.SetDateUpdated(*v)
	}
	return _u
}

// ClearDateUpdated clears the value of the "date_updated" field.
func (_u *NotificationUpdateOne) ClearDateUpdated() *NotificationUpdateOne {
	_u.mutation.ClearDateUpdated()
	return _u
}

// SetWorkflowExecutionID sets the "workflow_execution_id" field.
func (_u *NotificationUpdateOne) SetWorkflowExecutionID(v uuid.UUID) *NotificationUpdateOne {
	_u.mutation.SetWorkflowExecutionID(v)
	return _u
}

// SetNillableWorkflowExecutionID sets the "workflow_execution_id" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableWorkflowExecutionID(v *uuid.UUID) *NotificationUpdateOne {
	if v != nil {
		_u.SetWorkflowExecutionID(*v)
	}
	return _u
}

// SetWorkflowID sets the "workflow_id" field.
func (_u *NotificationUpdateOne) SetWorkflowID(v uuid.UUID) *NotificationUpdateOne {
	_u.mutation.SetWorkflowID(v)
	return _u
}

// SetNillableWorkflowID sets the "workflow_id" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableWorkflowID(v *uuid.UUID) *NotificationUpdateOne {
	if v != nil {
		_u.SetWorkflowID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *NotificationUpdateOne) SetTitle(v string) *NotificationUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableTitle(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *NotificationUpdateOne) SetMessage(v string) *NotificationUpdateOne {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableMessage(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// ClearMessage clears the value of the "message" field.
func (_u *NotificationUpdateOne) ClearMessage() *NotificationUpdateOne {
	_u.mutation.ClearMessage()
	return _u
}

// SetStatus sets the "status" field.
func (_u *NotificationUpdateOne) SetStatus(v notification.Status) *NotificationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableStatus(v *notification.Status) *NotificationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSeverity sets the "severity" field.
func (_u *NotificationUpdateOne) SetSeverity(v notification.Severity) *NotificationUpdateOne {
	_u.mutation.SetSeverity(v)
	return _u
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableSeverity(v *notification.Severity) *NotificationUpdateOne {
	if v != nil {
		_u.SetSeverity(*v)
	}
	return _u
}

// SetWorkflow sets the "workflow" edge to the Workflow entity.
func (_u *NotificationUpdateOne) SetWorkflow(v *Workflow) *NotificationUpdateOne {
	return _u.SetWorkflowID(v.ID)
}

// SetWorkflowExecution sets the "workflow_execution" edge to the WorkflowExecution entity.
func (_u *NotificationUpdateOne) SetWorkflowExecution(v *WorkflowExecution) *NotificationUpdateOne {
	return _u.SetWorkflowExecutionID(v.ID)
}

// Mutation returns the NotificationMutation object of the builder.
func (_u *NotificationUpdateOne) Mutation() *NotificationMutation {
	return _u.mutation
}

// ClearWorkflow clears the "workflow" edge to the Workflow entity.
func (_u *NotificationUpdateOne) ClearWorkflow() *NotificationUpdateOne {
	_u.mutation.ClearWorkflow()
	return _u
}

// ClearWorkflowExecution clears the "workflow_execution" edge to the WorkflowExecution entity.
func (_u *NotificationUpdateOne) ClearWorkflowExecution() *NotificationUpdateOne {
	_u.mutation.ClearWorkflowExecution()
	return _u
}

// Where appends a list predicates to the NotificationUpdate builder.
func (_u *NotificationUpdateOne) Where(ps ...predicate.Notification) *NotificationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NotificationUpdateOne) Select(field string, fields ...string) *NotificationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Notification entity.
func (_u *NotificationUpdateOne) Save(ctx context.Context) (*Notification, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationUpdateOne) SaveX(ctx context.Context) *Notification {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NotificationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := notification.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Notification.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Message(); ok {
		if err := notification.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "Notification.message": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := notification.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Notification.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Severity(); ok {
		if err := notification.SeverityValidator(v); err != nil {
			return &ValidationError{Name: "severity", err: fmt.Errorf(`ent: validator failed for field "Notification.severity": %w`, err)}
		}
	}
	if _u.mutation.WorkflowCleared() && len(_u.mutation.WorkflowIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Notification.workflow"`)
	}
	if _u.mutation.WorkflowExecutionCleared() && len(_u.mutation.WorkflowExecutionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Notification.workflow_execution"`)
	}
	return nil
}

func (_u *NotificationUpdateOne) sqlSave(ctx context.Context) (_node *Notification, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notification.Table, notification.Columns, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Notification.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notification.FieldID)
		for _, f := range fields {
			if !notification.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notification.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DateUpdated(); ok {
		_spec.SetField(notification.FieldDateUpdated, field.TypeTime, value)
	}
	if _u.mutation.DateUpdatedCleared() {
		_spec.ClearField(notification.FieldDateUpdated, field.TypeTime)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(notification.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(notification.FieldMessage, field.TypeString, value)
	}
	if _u.mutation.MessageCleared() {
		_spec.ClearField(notification.FieldMessage, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(notification.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Severity(); ok {
		_spec.SetField(notification.FieldSeverity, field.TypeEnum, value)
	}
	if _u.mutation.WorkflowCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notification.WorkflowTable,
			Columns: []string{notification.WorkflowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkflowIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notification.WorkflowTable,
			Columns: []string{notification.WorkflowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WorkflowExecutionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notification.WorkflowExecutionTable,
			Columns: []string{notification.WorkflowExecutionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflowexecution.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkflowExecutionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notification.WorkflowExecutionTable,
			Columns: []string{notification.WorkflowExecutionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflowexecution.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Notification{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
