// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"react-go-workflow/ent/steptype"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// StepType is the model entity for the StepType schema.
type StepType struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// DateCreated holds the value of the "date_created" field.
	DateCreated time.Time `json:"date_created,omitempty"`
	// DateUpdated holds the value of the "date_updated" field.
	DateUpdated *time.Time `json:"date_updated,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// DisplayName holds the value of the "display_name" field.
	DisplayName string `json:"display_name,omitempty"`
	// Category holds the value of the "category" field.
	Category steptype.Category `json:"category,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Icon holds the value of the "icon" field.
	Icon string `json:"icon,omitempty"`
	// ConfigSchema holds the value of the "config_schema" field.
	ConfigSchema map[string]interface{} `json:"config_schema,omitempty"`
	// InputSchema holds the value of the "input_schema" field.
	InputSchema map[string]interface{} `json:"input_schema,omitempty"`
	// OutputSchema holds the value of the "output_schema" field.
	OutputSchema map[string]interface{} `json:"output_schema,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the StepTypeQuery when eager-loading is set.
	Edges        StepTypeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// StepTypeEdges holds the relations/edges for other nodes in the graph.
type StepTypeEdges struct {
	// Steps holds the value of the steps edge.
	Steps []*Step `json:"steps,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// StepsOrErr returns the Steps value or an error if the edge
// was not loaded in eager-loading.
func (e StepTypeEdges) StepsOrErr() ([]*Step, error) {
	if e.loadedTypes[0] {
		return e.Steps, nil
	}
	return nil, &NotLoadedError{edge: "steps"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*StepType) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case steptype.FieldConfigSchema, steptype.FieldInputSchema, steptype.FieldOutputSchema:
			values[i] = new([]byte)
		case steptype.FieldIsActive:
			values[i] = new(sql.NullBool)
		case steptype.FieldName, steptype.FieldDisplayName, steptype.FieldCategory, steptype.FieldDescription, steptype.FieldIcon:
			values[i] = new(sql.NullString)
		case steptype.FieldDateCreated, steptype.FieldDateUpdated:
			values[i] = new(sql.NullTime)
		case steptype.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the StepType fields.
func (_m *StepType) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case steptype.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case steptype.FieldDateCreated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_created", values[i])
			} else if value.Valid {
				_m.DateCreated = value.Time
			}
		case steptype.FieldDateUpdated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_updated", values[i])
			} else if value.Valid {
				_m.DateUpdated = new(time.Time)
				*_m.DateUpdated = value.Time
			}
		case steptype.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case steptype.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				_m.DisplayName = value.String
			}
		case steptype.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				_m.Category = steptype.Category(value.String)
			}
		case steptype.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case steptype.FieldIcon:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field icon", values[i])
			} else if value.Valid {
				_m.Icon = value.String
			}
		case steptype.FieldConfigSchema:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field config_schema", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ConfigSchema); err != nil {
					return fmt.Errorf("unmarshal field config_schema: %w", err)
				}
			}
		case steptype.FieldInputSchema:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field input_schema", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.InputSchema); err != nil {
					return fmt.Errorf("unmarshal field input_schema: %w", err)
				}
			}
		case steptype.FieldOutputSchema:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field output_schema", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.OutputSchema); err != nil {
					return fmt.Errorf("unmarshal field output_schema: %w", err)
				}
			}
		case steptype.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the StepType.
// This includes values selected through modifiers, order, etc.
func (_m *StepType) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySteps queries the "steps" edge of the StepType entity.
func (_m *StepType) QuerySteps() *StepQuery {
	return NewStepTypeClient(_m.config).QuerySteps(_m)
}

// Update returns a builder for updating this StepType.
// Note that you need to call StepType.Unwrap() before calling this method if this StepType
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *StepType) Update() *StepTypeUpdateOne {
	return NewStepTypeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the StepType entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *StepType) Unwrap() *StepType {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: StepType is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *StepType) String() string {
	var builder strings.Builder
	builder.WriteString("StepType(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("date_created=")
	builder.WriteString(_m.DateCreated.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DateUpdated; v != nil {
		builder.WriteString("date_updated=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("display_name=")
	builder.WriteString(_m.DisplayName)
	builder.WriteString(", ")
	builder.WriteString("category=")
	builder.WriteString(fmt.Sprintf("%v", _m.Category))
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("icon=")
	builder.WriteString(_m.Icon)
	builder.WriteString(", ")
	builder.WriteString("config_schema=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConfigSchema))
	builder.WriteString(", ")
	builder.WriteString("input_schema=")
	builder.WriteString(fmt.Sprintf("%v", _m.InputSchema))
	builder.WriteString(", ")
	builder.WriteString("output_schema=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutputSchema))
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteByte(')')
	return builder.String()
}

// StepTypes is a parsable slice of StepType.
type StepTypes []*StepType
