// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"react-go-workflow/ent/step"
	"react-go-workflow/ent/steptype"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// StepTypeCreate is the builder for creating a StepType entity.
type StepTypeCreate struct {
	config
	mutation *StepTypeMutation
	hooks    []Hook
}

// SetDateCreated sets the "date_created" field.
func (_c *StepTypeCreate) SetDateCreated(v time.Time) *StepTypeCreate {
	_c.mutation.SetDateCreated(v)
	return _c
}

// SetNillableDateCreated sets the "date_created" field if the given value is not nil.
func (_c *StepTypeCreate) SetNillableDateCreated(v *time.Time) *StepTypeCreate {
	if v != nil {
		_c.SetDateCreated(*v)
	}
	return _c
}

// SetDateUpdated sets the "date_updated" field.
func (_c *StepTypeCreate) SetDateUpdated(v time.Time) *StepTypeCreate {
	_c.mutation.SetDateUpdated(v)
	return _c
}

// SetNillableDateUpdated sets the "date_updated" field if the given value is not nil.
func (_c *StepTypeCreate) SetNillableDateUpdated(v *time.Time) *StepTypeCreate {
	if v != nil {
		_c.SetDateUpdated(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *StepTypeCreate) SetName(v string) *StepTypeCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDisplayName sets the "display_name" field.
func (_c *StepTypeCreate) SetDisplayName(v string) *StepTypeCreate {
	_c.mutation.SetDisplayName(v)
	return _c
}

// SetCategory sets the "category" field.
func (_c *StepTypeCreate) SetCategory(v steptype.Category) *StepTypeCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *StepTypeCreate) SetDescription(v string) *StepTypeCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *StepTypeCreate) SetNillableDescription(v *string) *StepTypeCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetIcon sets the "icon" field.
func (_c *StepTypeCreate) SetIcon(v string) *StepTypeCreate {
	_c.mutation.SetIcon(v)
	return _c
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_c *StepTypeCreate) SetNillableIcon(v *string) *StepTypeCreate {
	if v != nil {
		_c.SetIcon(*v)
	}
	return _c
}

// SetConfigSchema sets the "config_schema" field.
func (_c *StepTypeCreate) SetConfigSchema(v map[string]interface{}) *StepTypeCreate {
	_c.mutation.SetConfigSchema(v)
	return _c
}

// SetInputSchema sets the "input_schema" field.
func (_c *StepTypeCreate) SetInputSchema(v map[string]interface{}) *StepTypeCreate {
	_c.mutation.SetInputSchema(v)
	return _c
}

// SetOutputSchema sets the "output_schema" field.
func (_c *StepTypeCreate) SetOutputSchema(v map[string]interface{}) *StepTypeCreate {
	_c.mutation.SetOutputSchema(v)
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *StepTypeCreate) SetIsActive(v bool) *StepTypeCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *StepTypeCreate) SetNillableIsActive(v *bool) *StepTypeCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *StepTypeCreate) SetID(v uuid.UUID) *StepTypeCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *StepTypeCreate) SetNillableID(v *uuid.UUID) *StepTypeCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddStepIDs adds the "steps" edge to the Step entity by IDs.
func (_c *StepTypeCreate) AddStepIDs(ids ...uuid.UUID) *StepTypeCreate {
	_c.mutation.AddStepIDs(ids...)
	return _c
}

// AddSteps adds the "steps" edges to the Step entity.
func (_c *StepTypeCreate) AddSteps(v ...*Step) *StepTypeCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddStepIDs(ids...)
}

// Mutation returns the StepTypeMutation object of the builder.
func (_c *StepTypeCreate) Mutation() *StepTypeMutation {
	return _c.mutation
}

// Save creates the StepType in the database.
func (_c *StepTypeCreate) Save(ctx context.Context) (*StepType, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *StepTypeCreate) SaveX(ctx context.Context) *StepType {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StepTypeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StepTypeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *StepTypeCreate) defaults() error {
	if _, ok := _c.mutation.DateCreated(); !ok {
		if steptype.DefaultDateCreated == nil {
			return fmt.Errorf("ent: uninitialized steptype.DefaultDateCreated (forgotten import ent/runtime?)")
		}
		v := steptype.DefaultDateCreated()
		_c.mutation.SetDateCreated(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := steptype.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		if steptype.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized steptype.DefaultID (forgotten import ent/runtime?)")
		}
		v := steptype.DefaultID()
		_c.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *StepTypeCreate) check() error {
	if _, ok := _c.mutation.DateCreated(); !ok {
		return &ValidationError{Name: "date_created", err: errors.New(`ent: missing required field "StepType.date_created"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "StepType.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := steptype.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "StepType.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DisplayName(); !ok {
		return &ValidationError{Name: "display_name", err: errors.New(`ent: missing required field "StepType.display_name"`)}
	}
	if v, ok := _c.mutation.DisplayName(); ok {
		if err := steptype.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "StepType.display_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "StepType.category"`)}
	}
	if v, ok := _c.mutation.Category(); ok {
		if err := steptype.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "StepType.category": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := steptype.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "StepType.description": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Icon(); ok {
		if err := steptype.IconValidator(v); err != nil {
			return &ValidationError{Name: "icon", err: fmt.Errorf(`ent: validator failed for field "StepType.icon": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "StepType.is_active"`)}
	}
	return nil
}

func (_c *StepTypeCreate) sqlSave(ctx context.Context) (*StepType, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *StepTypeCreate) createSpec() (*StepType, *sqlgraph.CreateSpec) {
	var (
		_node = &StepType{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(steptype.Table, sqlgraph.NewFieldSpec(steptype.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.DateCreated(); ok {
		_spec.SetField(steptype.FieldDateCreated, field.TypeTime, value)
		_node.DateCreated = value
	}
	if value, ok := _c.mutation.DateUpdated(); ok {
		_spec.SetField(steptype.FieldDateUpdated, field.TypeTime, value)
		_node.DateUpdated = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(steptype.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.DisplayName(); ok {
		_spec.SetField(steptype.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(steptype.FieldCategory, field.TypeEnum, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(steptype.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Icon(); ok {
		_spec.SetField(steptype.FieldIcon, field.TypeString, value)
		_node.Icon = value
	}
	if value, ok := _c.mutation.ConfigSchema(); ok {
		_spec.SetField(steptype.FieldConfigSchema, field.TypeJSON, value)
		_node.ConfigSchema = value
	}
	if value, ok := _c.mutation.InputSchema(); ok {
		_spec.SetField(steptype.FieldInputSchema, field.TypeJSON, value)
		_node.InputSchema = value
	}
	if value, ok := _c.mutation.OutputSchema(); ok {
		_spec.SetField(steptype.FieldOutputSchema, field.TypeJSON, value)
		_node.OutputSchema = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(steptype.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if nodes := _c.mutation.StepsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   steptype.StepsTable,
			Columns: []string{steptype.StepsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(step.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// StepTypeCreateBulk is the builder for creating many StepType entities in bulk.
type StepTypeCreateBulk struct {
	config
	err      error
	builders []*StepTypeCreate
}

// Save creates the StepType entities in the database.
func (_c *StepTypeCreateBulk) Save(ctx context.Context) ([]*StepType, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*StepType, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StepTypeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *StepTypeCreateBulk) SaveX(ctx context.Context) []*StepType {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StepTypeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StepTypeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
