// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"react-go-workflow/ent/step"
	"react-go-workflow/ent/steptype"
	"react-go-workflow/ent/workflow"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Step is the model entity for the Step schema.
type Step struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// DateCreated holds the value of the "date_created" field.
	DateCreated time.Time `json:"date_created,omitempty"`
	// DateUpdated holds the value of the "date_updated" field.
	DateUpdated *time.Time `json:"date_updated,omitempty"`
	// WorkflowID holds the value of the "workflow_id" field.
	WorkflowID uuid.UUID `json:"workflow_id,omitempty"`
	// StepTypeID holds the value of the "step_type_id" field.
	StepTypeID uuid.UUID `json:"step_type_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Config holds the value of the "config" field.
	Config map[string]interface{} `json:"config,omitempty"`
	// PositionX holds the value of the "position_x" field.
	PositionX float64 `json:"position_x,omitempty"`
	// PositionY holds the value of the "position_y" field.
	PositionY float64 `json:"position_y,omitempty"`
	// InputMapping holds the value of the "input_mapping" field.
	InputMapping map[string]interface{} `json:"input_mapping,omitempty"`
	// TimeoutSeconds holds the value of the "timeout_seconds" field.
	TimeoutSeconds int `json:"timeout_seconds,omitempty"`
	// RetryCount holds the value of the "retry_count" field.
	RetryCount int `json:"retry_count,omitempty"`
	// RetryBackoff holds the value of the "retry_backoff" field.
	RetryBackoff step.RetryBackoff `json:"retry_backoff,omitempty"`
	// RetryDelayMs holds the value of the "retry_delay_ms" field.
	RetryDelayMs int `json:"retry_delay_ms,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the StepQuery when eager-loading is set.
	Edges        StepEdges `json:"edges"`
	selectValues sql.SelectValues
}

// StepEdges holds the relations/edges for other nodes in the graph.
type StepEdges struct {
	// Workflow holds the value of the workflow edge.
	Workflow *Workflow `json:"workflow,omitempty"`
	// StepType holds the value of the step_type edge.
	StepType *StepType `json:"step_type,omitempty"`
	// SourceEdges holds the value of the source_edges edge.
	SourceEdges []*Edge `json:"source_edges,omitempty"`
	// TargetEdges holds the value of the target_edges edge.
	TargetEdges []*Edge `json:"target_edges,omitempty"`
	// StepExecutions holds the value of the step_executions edge.
	StepExecutions []*StepExecution `json:"step_executions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// WorkflowOrErr returns the Workflow value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e StepEdges) WorkflowOrErr() (*Workflow, error) {
	if e.Workflow != nil {
		return e.Workflow, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: workflow.Label}
	}
	return nil, &NotLoadedError{edge: "workflow"}
}

// StepTypeOrErr returns the StepType value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e StepEdges) StepTypeOrErr() (*StepType, error) {
	if e.StepType != nil {
		return e.StepType, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: steptype.Label}
	}
	return nil, &NotLoadedError{edge: "step_type"}
}

// SourceEdgesOrErr returns the SourceEdges value or an error if the edge
// was not loaded in eager-loading.
func (e StepEdges) SourceEdgesOrErr() ([]*Edge, error) {
	if e.loadedTypes[2] {
		return e.SourceEdges, nil
	}
	return nil, &NotLoadedError{edge: "source_edges"}
}

// TargetEdgesOrErr returns the TargetEdges value or an error if the edge
// was not loaded in eager-loading.
func (e StepEdges) TargetEdgesOrErr() ([]*Edge, error) {
	if e.loadedTypes[3] {
		return e.TargetEdges, nil
	}
	return nil, &NotLoadedError{edge: "target_edges"}
}

// StepExecutionsOrErr returns the StepExecutions value or an error if the edge
// was not loaded in eager-loading.
func (e StepEdges) StepExecutionsOrErr() ([]*StepExecution, error) {
	if e.loadedTypes[4] {
		return e.StepExecutions, nil
	}
	return nil, &NotLoadedError{edge: "step_executions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Step) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case step.FieldConfig, step.FieldInputMapping:
			values[i] = new([]byte)
		case step.FieldPositionX, step.FieldPositionY:
			values[i] = new(sql.NullFloat64)
		case step.FieldTimeoutSeconds, step.FieldRetryCount, step.FieldRetryDelayMs:
			values[i] = new(sql.NullInt64)
		case step.FieldName, step.FieldDescription, step.FieldRetryBackoff:
			values[i] = new(sql.NullString)
		case step.FieldDateCreated, step.FieldDateUpdated:
			values[i] = new(sql.NullTime)
		case step.FieldID, step.FieldWorkflowID, step.FieldStepTypeID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Step fields.
func (_m *Step) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case step.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case step.FieldDateCreated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_created", values[i])
			} else if value.Valid {
				_m.DateCreated = value.Time
			}
		case step.FieldDateUpdated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_updated", values[i])
			} else if value.Valid {
				_m.DateUpdated = new(time.Time)
				*_m.DateUpdated = value.Time
			}
		case step.FieldWorkflowID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field workflow_id", values[i])
			} else if value != nil {
				_m.WorkflowID = *value
			}
		case step.FieldStepTypeID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field step_type_id", values[i])
			} else if value != nil {
				_m.StepTypeID = *value
			}
		case step.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case step.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case step.FieldConfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field config", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Config); err != nil {
					return fmt.Errorf("unmarshal field config: %w", err)
				}
			}
		case step.FieldPositionX:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field position_x", values[i])
			} else if value.Valid {
				_m.PositionX = value.Float64
			}
		case step.FieldPositionY:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field position_y", values[i])
			} else if value.Valid {
				_m.PositionY = value.Float64
			}
		case step.FieldInputMapping:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field input_mapping", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.InputMapping); err != nil {
					return fmt.Errorf("unmarshal field input_mapping: %w", err)
				}
			}
		case step.FieldTimeoutSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field timeout_seconds", values[i])
			} else if value.Valid {
				_m.TimeoutSeconds = int(value.Int64)
			}
		case step.FieldRetryCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field retry_count", values[i])
			} else if value.Valid {
				_m.RetryCount = int(value.Int64)
			}
		case step.FieldRetryBackoff:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field retry_backoff", values[i])
			} else if value.Valid {
				_m.RetryBackoff = step.RetryBackoff(value.String)
			}
		case step.FieldRetryDelayMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field retry_delay_ms", values[i])
			} else if value.Valid {
				_m.RetryDelayMs = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Step.
// This includes values selected through modifiers, order, etc.
func (_m *Step) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryWorkflow queries the "workflow" edge of the Step entity.
func (_m *Step) QueryWorkflow() *WorkflowQuery {
	return NewStepClient(_m.config).QueryWorkflow(_m)
}

// QueryStepType queries the "step_type" edge of the Step entity.
func (_m *Step) QueryStepType() *StepTypeQuery {
	return NewStepClient(_m.config).QueryStepType(_m)
}

// QuerySourceEdges queries the "source_edges" edge of the Step entity.
func (_m *Step) QuerySourceEdges() *EdgeQuery {
	return NewStepClient(_m.config).QuerySourceEdges(_m)
}

// QueryTargetEdges queries the "target_edges" edge of the Step entity.
func (_m *Step) QueryTargetEdges() *EdgeQuery {
	return NewStepClient(_m.config).QueryTargetEdges(_m)
}

// QueryStepExecutions queries the "step_executions" edge of the Step entity.
func (_m *Step) QueryStepExecutions() *StepExecutionQuery {
	return NewStepClient(_m.config).QueryStepExecutions(_m)
}

// Update returns a builder for updating this Step.
// Note that you need to call Step.Unwrap() before calling this method if this Step
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Step) Update() *StepUpdateOne {
	return NewStepClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Step entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Step) Unwrap() *Step {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Step is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Step) String() string {
	var builder strings.Builder
	builder.WriteString("Step(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("date_created=")
	builder.WriteString(_m.DateCreated.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DateUpdated; v != nil {
		builder.WriteString("date_updated=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("workflow_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.WorkflowID))
	builder.WriteString(", ")
	builder.WriteString("step_type_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.StepTypeID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("config=")
	builder.WriteString(fmt.Sprintf("%v", _m.Config))
	builder.WriteString(", ")
	builder.WriteString("position_x=")
	builder.WriteString(fmt.Sprintf("%v", _m.PositionX))
	builder.WriteString(", ")
	builder.WriteString("position_y=")
	builder.WriteString(fmt.Sprintf("%v", _m.PositionY))
	builder.WriteString(", ")
	builder.WriteString("input_mapping=")
	builder.WriteString(fmt.Sprintf("%v", _m.InputMapping))
	builder.WriteString(", ")
	builder.WriteString("timeout_seconds=")
	builder.WriteString(fmt.Sprintf("%v", _m.TimeoutSeconds))
	builder.WriteString(", ")
	builder.WriteString("retry_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.RetryCount))
	builder.WriteString(", ")
	builder.WriteString("retry_backoff=")
	builder.WriteString(fmt.Sprintf("%v", _m.RetryBackoff))
	builder.WriteString(", ")
	builder.WriteString("retry_delay_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.RetryDelayMs))
	builder.WriteByte(')')
	return builder.String()
}

// Steps is a parsable slice of Step.
type Steps []*Step
