// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"react-go-workflow/ent/workflow"
	"react-go-workflow/ent/workflowexecution"
	"react-go-workflow/ent/workflowversion"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// WorkflowExecution is the model entity for the WorkflowExecution schema.
type WorkflowExecution struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// DateCreated holds the value of the "date_created" field.
	DateCreated time.Time `json:"date_created,omitempty"`
	// DateUpdated holds the value of the "date_updated" field.
	DateUpdated *time.Time `json:"date_updated,omitempty"`
	// WorkflowID holds the value of the "workflow_id" field.
	WorkflowID uuid.UUID `json:"workflow_id,omitempty"`
	// WorkflowVersionID holds the value of the "workflow_version_id" field.
	WorkflowVersionID *uuid.UUID `json:"workflow_version_id,omitempty"`
	// TriggerType holds the value of the "trigger_type" field.
	TriggerType workflowexecution.TriggerType `json:"trigger_type,omitempty"`
	// Status holds the value of the "status" field.
	Status workflowexecution.Status `json:"status,omitempty"`
	// Input holds the value of the "input" field.
	Input map[string]interface{} `json:"input,omitempty"`
	// Output holds the value of the "output" field.
	Output map[string]interface{} `json:"output,omitempty"`
	// Error holds the value of the "error" field.
	Error string `json:"error,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt *time.Time `json:"started_at,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the WorkflowExecutionQuery when eager-loading is set.
	Edges        WorkflowExecutionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// WorkflowExecutionEdges holds the relations/edges for other nodes in the graph.
type WorkflowExecutionEdges struct {
	// Workflow holds the value of the workflow edge.
	Workflow *Workflow `json:"workflow,omitempty"`
	// WorkflowVersion holds the value of the workflow_version edge.
	WorkflowVersion *WorkflowVersion `json:"workflow_version,omitempty"`
	// StepExecutions holds the value of the step_executions edge.
	StepExecutions []*StepExecution `json:"step_executions,omitempty"`
	// Notifications holds the value of the notifications edge.
	Notifications []*Notification `json:"notifications,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// WorkflowOrErr returns the Workflow value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e WorkflowExecutionEdges) WorkflowOrErr() (*Workflow, error) {
	if e.Workflow != nil {
		return e.Workflow, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: workflow.Label}
	}
	return nil, &NotLoadedError{edge: "workflow"}
}

// WorkflowVersionOrErr returns the WorkflowVersion value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e WorkflowExecutionEdges) WorkflowVersionOrErr() (*WorkflowVersion, error) {
	if e.WorkflowVersion != nil {
		return e.WorkflowVersion, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: workflowversion.Label}
	}
	return nil, &NotLoadedError{edge: "workflow_version"}
}

// StepExecutionsOrErr returns the StepExecutions value or an error if the edge
// was not loaded in eager-loading.
func (e WorkflowExecutionEdges) StepExecutionsOrErr() ([]*StepExecution, error) {
	if e.loadedTypes[2] {
		return e.StepExecutions, nil
	}
	return nil, &NotLoadedError{edge: "step_executions"}
}

// NotificationsOrErr returns the Notifications value or an error if the edge
// was not loaded in eager-loading.
func (e WorkflowExecutionEdges) NotificationsOrErr() ([]*Notification, error) {
	if e.loadedTypes[3] {
		return e.Notifications, nil
	}
	return nil, &NotLoadedError{edge: "notifications"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WorkflowExecution) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case workflowexecution.FieldWorkflowVersionID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case workflowexecution.FieldInput, workflowexecution.FieldOutput:
			values[i] = new([]byte)
		case workflowexecution.FieldTriggerType, workflowexecution.FieldStatus, workflowexecution.FieldError:
			values[i] = new(sql.NullString)
		case workflowexecution.FieldDateCreated, workflowexecution.FieldDateUpdated, workflowexecution.FieldStartedAt, workflowexecution.FieldCompletedAt:
			values[i] = new(sql.NullTime)
		case workflowexecution.FieldID, workflowexecution.FieldWorkflowID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WorkflowExecution fields.
func (_m *WorkflowExecution) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case workflowexecution.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case workflowexecution.FieldDateCreated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_created", values[i])
			} else if value.Valid {
				_m.DateCreated = value.Time
			}
		case workflowexecution.FieldDateUpdated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_updated", values[i])
			} else if value.Valid {
				_m.DateUpdated = new(time.Time)
				*_m.DateUpdated = value.Time
			}
		case workflowexecution.FieldWorkflowID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field workflow_id", values[i])
			} else if value != nil {
				_m.WorkflowID = *value
			}
		case workflowexecution.FieldWorkflowVersionID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field workflow_version_id", values[i])
			} else if value.Valid {
				_m.WorkflowVersionID = new(uuid.UUID)
				*_m.WorkflowVersionID = *value.S.(*uuid.UUID)
			}
		case workflowexecution.FieldTriggerType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trigger_type", values[i])
			} else if value.Valid {
				_m.TriggerType = workflowexecution.TriggerType(value.String)
			}
		case workflowexecution.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = workflowexecution.Status(value.String)
			}
		case workflowexecution.FieldInput:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field input", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Input); err != nil {
					return fmt.Errorf("unmarshal field input: %w", err)
				}
			}
		case workflowexecution.FieldOutput:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field output", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Output); err != nil {
					return fmt.Errorf("unmarshal field output: %w", err)
				}
			}
		case workflowexecution.FieldError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error", values[i])
			} else if value.Valid {
				_m.Error = value.String
			}
		case workflowexecution.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = new(time.Time)
				*_m.StartedAt = value.Time
			}
		case workflowexecution.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WorkflowExecution.
// This includes values selected through modifiers, order, etc.
func (_m *WorkflowExecution) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryWorkflow queries the "workflow" edge of the WorkflowExecution entity.
func (_m *WorkflowExecution) QueryWorkflow() *WorkflowQuery {
	return NewWorkflowExecutionClient(_m.config).QueryWorkflow(_m)
}

// QueryWorkflowVersion queries the "workflow_version" edge of the WorkflowExecution entity.
func (_m *WorkflowExecution) QueryWorkflowVersion() *WorkflowVersionQuery {
	return NewWorkflowExecutionClient(_m.config).QueryWorkflowVersion(_m)
}

// QueryStepExecutions queries the "step_executions" edge of the WorkflowExecution entity.
func (_m *WorkflowExecution) QueryStepExecutions() *StepExecutionQuery {
	return NewWorkflowExecutionClient(_m.config).QueryStepExecutions(_m)
}

// QueryNotifications queries the "notifications" edge of the WorkflowExecution entity.
func (_m *WorkflowExecution) QueryNotifications() *NotificationQuery {
	return NewWorkflowExecutionClient(_m.config).QueryNotifications(_m)
}

// Update returns a builder for updating this WorkflowExecution.
// Note that you need to call WorkflowExecution.Unwrap() before calling this method if this WorkflowExecution
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *WorkflowExecution) Update() *WorkflowExecutionUpdateOne {
	return NewWorkflowExecutionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the WorkflowExecution entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *WorkflowExecution) Unwrap() *WorkflowExecution {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: WorkflowExecution is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *WorkflowExecution) String() string {
	var builder strings.Builder
	builder.WriteString("WorkflowExecution(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("date_created=")
	builder.WriteString(_m.DateCreated.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DateUpdated; v != nil {
		builder.WriteString("date_updated=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("workflow_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.WorkflowID))
	builder.WriteString(", ")
	if v := _m.WorkflowVersionID; v != nil {
		builder.WriteString("workflow_version_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("trigger_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.TriggerType))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("input=")
	builder.WriteString(fmt.Sprintf("%v", _m.Input))
	builder.WriteString(", ")
	builder.WriteString("output=")
	builder.WriteString(fmt.Sprintf("%v", _m.Output))
	builder.WriteString(", ")
	builder.WriteString("error=")
	builder.WriteString(_m.Error)
	builder.WriteString(", ")
	if v := _m.StartedAt; v != nil {
		builder.WriteString("started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// WorkflowExecutions is a parsable slice of WorkflowExecution.
type WorkflowExecutions []*WorkflowExecution
