// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"react-go-workflow/ent/canvasnote"
	"react-go-workflow/ent/edge"
	"react-go-workflow/ent/notification"
	"react-go-workflow/ent/notificationsetting"
	"react-go-workflow/ent/predicate"
	"react-go-workflow/ent/step"
	"react-go-workflow/ent/workflow"
	"react-go-workflow/ent/workflowexecution"
	"react-go-workflow/ent/workflowversion"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// WorkflowQuery is the builder for querying Workflow entities.
type WorkflowQuery struct {
	config
	ctx                      *QueryContext
	order                    []workflow.OrderOption
	inters                   []Interceptor
	predicates               []predicate.Workflow
	withSteps                *StepQuery
	withEdges                *EdgeQuery
	withCanvasNotes          *CanvasNoteQuery
	withVersions             *WorkflowVersionQuery
	withExecutions           *WorkflowExecutionQuery
	withNotificationSettings *NotificationSettingQuery
	withNotifications        *NotificationQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WorkflowQuery builder.
func (_q *WorkflowQuery) Where(ps ...predicate.Workflow) *WorkflowQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *WorkflowQuery) Limit(limit int) *WorkflowQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *WorkflowQuery) Offset(offset int) *WorkflowQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *WorkflowQuery) Unique(unique bool) *WorkflowQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *WorkflowQuery) Order(o ...workflow.OrderOption) *WorkflowQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QuerySteps chains the current query on the "steps" edge.
func (_q *WorkflowQuery) QuerySteps() *StepQuery {
	query := (&StepClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(workflow.Table, workflow.FieldID, selector),
			sqlgraph.To(step.Table, step.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, workflow.StepsTable, workflow.StepsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryEdges chains the current query on the "edges" edge.
func (_q *WorkflowQuery) QueryEdges() *EdgeQuery {
	query := (&EdgeClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(workflow.Table, workflow.FieldID, selector),
			sqlgraph.To(edge.Table, edge.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, workflow.EdgesTable, workflow.EdgesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCanvasNotes chains the current query on the "canvas_notes" edge.
func (_q *WorkflowQuery) QueryCanvasNotes() *CanvasNoteQuery {
	query := (&CanvasNoteClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(workflow.Table, workflow.FieldID, selector),
			sqlgraph.To(canvasnote.Table, canvasnote.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, workflow.CanvasNotesTable, workflow.CanvasNotesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryVersions chains the current query on the "versions" edge.
func (_q *WorkflowQuery) QueryVersions() *WorkflowVersionQuery {
	query := (&WorkflowVersionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(workflow.Table, workflow.FieldID, selector),
			sqlgraph.To(workflowversion.Table, workflowversion.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, workflow.VersionsTable, workflow.VersionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryExecutions chains the current query on the "executions" edge.
func (_q *WorkflowQuery) QueryExecutions() *WorkflowExecutionQuery {
	query := (&WorkflowExecutionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(workflow.Table, workflow.FieldID, selector),
			sqlgraph.To(workflowexecution.Table, workflowexecution.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, workflow.ExecutionsTable, workflow.ExecutionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryNotificationSettings chains the current query on the "notification_settings" edge.
func (_q *WorkflowQuery) QueryNotificationSettings() *NotificationSettingQuery {
	query := (&NotificationSettingClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(workflow.Table, workflow.FieldID, selector),
			sqlgraph.To(notificationsetting.Table, notificationsetting.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, workflow.NotificationSettingsTable, workflow.NotificationSettingsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryNotifications chains the current query on the "notifications" edge.
func (_q *WorkflowQuery) QueryNotifications() *NotificationQuery {
	query := (&NotificationClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(workflow.Table, workflow.FieldID, selector),
			sqlgraph.To(notification.Table, notification.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, workflow.NotificationsTable, workflow.NotificationsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Workflow entity from the query.
// Returns a *NotFoundError when no Workflow was found.
func (_q *WorkflowQuery) First(ctx context.Context) (*Workflow, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{workflow.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *WorkflowQuery) FirstX(ctx context.Context) *Workflow {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Workflow ID from the query.
// Returns a *NotFoundError when no Workflow ID was found.
func (_q *WorkflowQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{workflow.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *WorkflowQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Workflow entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Workflow entity is found.
// Returns a *NotFoundError when no Workflow entities are found.
func (_q *WorkflowQuery) Only(ctx context.Context) (*Workflow, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{workflow.Label}
	default:
		return nil, &NotSingularError{workflow.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *WorkflowQuery) OnlyX(ctx context.Context) *Workflow {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Workflow ID in the query.
// Returns a *NotSingularError when more than one Workflow ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *WorkflowQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{workflow.Label}
	default:
		err = &NotSingularError{workflow.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *WorkflowQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Workflows.
func (_q *WorkflowQuery) All(ctx context.Context) ([]*Workflow, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Workflow, *WorkflowQuery]()
	return withInterceptors[[]*Workflow](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *WorkflowQuery) AllX(ctx context.Context) []*Workflow {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Workflow IDs.
func (_q *WorkflowQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(workflow.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *WorkflowQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *WorkflowQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*WorkflowQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *WorkflowQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *WorkflowQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *WorkflowQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WorkflowQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *WorkflowQuery) Clone() *WorkflowQuery {
	if _q == nil {
		return nil
	}
	return &WorkflowQuery{
		config:                   _q.config,
		ctx:                      _q.ctx.Clone(),
		order:                    append([]workflow.OrderOption{}, _q.order...),
		inters:                   append([]Interceptor{}, _q.inters...),
		predicates:               append([]predicate.Workflow{}, _q.predicates...),
		withSteps:                _q.withSteps.Clone(),
		withEdges:                _q.withEdges.Clone(),
		withCanvasNotes:          _q.withCanvasNotes.Clone(),
		withVersions:             _q.withVersions.Clone(),
		withExecutions:           _q.withExecutions.Clone(),
		withNotificationSettings: _q.withNotificationSettings.Clone(),
		withNotifications:        _q.withNotifications.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithSteps tells the query-builder to eager-load the nodes that are connected to
// the "steps" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *WorkflowQuery) WithSteps(opts ...func(*StepQuery)) *WorkflowQuery {
	query := (&StepClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSteps = query
	return _q
}

// WithEdges tells the query-builder to eager-load the nodes that are connected to
// the "edges" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *WorkflowQuery) WithEdges(opts ...func(*EdgeQuery)) *WorkflowQuery {
	query := (&EdgeClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withEdges = query
	return _q
}

// WithCanvasNotes tells the query-builder to eager-load the nodes that are connected to
// the "canvas_notes" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *WorkflowQuery) WithCanvasNotes(opts ...func(*CanvasNoteQuery)) *WorkflowQuery {
	query := (&CanvasNoteClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCanvasNotes = query
	return _q
}

// WithVersions tells the query-builder to eager-load the nodes that are connected to
// the "versions" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *WorkflowQuery) WithVersions(opts ...func(*WorkflowVersionQuery)) *WorkflowQuery {
	query := (&WorkflowVersionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withVersions = query
	return _q
}

// WithExecutions tells the query-builder to eager-load the nodes that are connected to
// the "executions" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *WorkflowQuery) WithExecutions(opts ...func(*WorkflowExecutionQuery)) *WorkflowQuery {
	query := (&WorkflowExecutionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withExecutions = query
	return _q
}

// WithNotificationSettings tells the query-builder to eager-load the nodes that are connected to
// the "notification_settings" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *WorkflowQuery) WithNotificationSettings(opts ...func(*NotificationSettingQuery)) *WorkflowQuery {
	query := (&NotificationSettingClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withNotificationSettings = query
	return _q
}

// WithNotifications tells the query-builder to eager-load the nodes that are connected to
// the "notifications" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *WorkflowQuery) WithNotifications(opts ...func(*NotificationQuery)) *WorkflowQuery {
	query := (&NotificationClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withNotifications = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		DateCreated time.Time `json:"date_created,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Workflow.Query().
//		GroupBy(workflow.FieldDateCreated).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *WorkflowQuery) GroupBy(field string, fields ...string) *WorkflowGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &WorkflowGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = workflow.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		DateCreated time.Time `json:"date_created,omitempty"`
//	}
//
//	client.Workflow.Query().
//		Select(workflow.FieldDateCreated).
//		Scan(ctx, &v)
func (_q *WorkflowQuery) Select(fields ...string) *WorkflowSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &WorkflowSelect{WorkflowQuery: _q}
	sbuild.label = workflow.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a WorkflowSelect configured with the given aggregations.
func (_q *WorkflowQuery) Aggregate(fns ...AggregateFunc) *WorkflowSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *WorkflowQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !workflow.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *WorkflowQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Workflow, error) {
	var (
		nodes       = []*Workflow{}
		_spec       = _q.querySpec()
		loadedTypes = [7]bool{
			_q.withSteps != nil,
			_q.withEdges != nil,
			_q.withCanvasNotes != nil,
			_q.withVersions != nil,
			_q.withExecutions != nil,
			_q.withNotificationSettings != nil,
			_q.withNotifications != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Workflow).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Workflow{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withSteps; query != nil {
		if err := _q.loadSteps(ctx, query, nodes,
			func(n *Workflow) { n.Edges.Steps = []*Step{} },
			func(n *Workflow, e *Step) { n.Edges.Steps = append(n.Edges.Steps, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withEdges; query != nil {
		if err := _q.loadEdges(ctx, query, nodes,
			func(n *Workflow) { n.Edges.Edges = []*Edge{} },
			func(n *Workflow, e *Edge) { n.Edges.Edges = append(n.Edges.Edges, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCanvasNotes; query != nil {
		if err := _q.loadCanvasNotes(ctx, query, nodes,
			func(n *Workflow) { n.Edges.CanvasNotes = []*CanvasNote{} },
			func(n *Workflow, e *CanvasNote) { n.Edges.CanvasNotes = append(n.Edges.CanvasNotes, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withVersions; query != nil {
		if err := _q.loadVersions(ctx, query, nodes,
			func(n *Workflow) { n.Edges.Versions = []*WorkflowVersion{} },
			func(n *Workflow, e *WorkflowVersion) { n.Edges.Versions = append(n.Edges.Versions, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withExecutions; query != nil {
		if err := _q.loadExecutions(ctx, query, nodes,
			func(n *Workflow) { n.Edges.Executions = []*WorkflowExecution{} },
			func(n *Workflow, e *WorkflowExecution) { n.Edges.Executions = append(n.Edges.Executions, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withNotificationSettings; query != nil {
		if err := _q.loadNotificationSettings(ctx, query, nodes,
			func(n *Workflow) { n.Edges.NotificationSettings = []*NotificationSetting{} },
			func(n *Workflow, e *NotificationSetting) {
				n.Edges.NotificationSettings = append(n.Edges.NotificationSettings, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := _q.withNotifications; query != nil {
		if err := _q.loadNotifications(ctx, query, nodes,
			func(n *Workflow) { n.Edges.Notifications = []*Notification{} },
			func(n *Workflow, e *Notification) { n.Edges.Notifications = append(n.Edges.Notifications, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *WorkflowQuery) loadSteps(ctx context.Context, query *StepQuery, nodes []*Workflow, init func(*Workflow), assign func(*Workflow, *Step)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Workflow)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(step.FieldWorkflowID)
	}
	query.Where(predicate.Step(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(workflow.StepsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.WorkflowID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "workflow_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *WorkflowQuery) loadEdges(ctx context.Context, query *EdgeQuery, nodes []*Workflow, init func(*Workflow), assign func(*Workflow, *Edge)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Workflow)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(edge.FieldWorkflowID)
	}
	query.Where(predicate.Edge(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(workflow.EdgesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.WorkflowID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "workflow_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *WorkflowQuery) loadCanvasNotes(ctx context.Context, query *CanvasNoteQuery, nodes []*Workflow, init func(*Workflow), assign func(*Workflow, *CanvasNote)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Workflow)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(canvasnote.FieldWorkflowID)
	}
	query.Where(predicate.CanvasNote(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(workflow.CanvasNotesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.WorkflowID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "workflow_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *WorkflowQuery) loadVersions(ctx context.Context, query *WorkflowVersionQuery, nodes []*Workflow, init func(*Workflow), assign func(*Workflow, *WorkflowVersion)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Workflow)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(workflowversion.FieldWorkflowID)
	}
	query.Where(predicate.WorkflowVersion(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(workflow.VersionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.WorkflowID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "workflow_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *WorkflowQuery) loadExecutions(ctx context.Context, query *WorkflowExecutionQuery, nodes []*Workflow, init func(*Workflow), assign func(*Workflow, *WorkflowExecution)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Workflow)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(workflowexecution.FieldWorkflowID)
	}
	query.Where(predicate.WorkflowExecution(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(workflow.ExecutionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.WorkflowID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "workflow_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *WorkflowQuery) loadNotificationSettings(ctx context.Context, query *NotificationSettingQuery, nodes []*Workflow, init func(*Workflow), assign func(*Workflow, *NotificationSetting)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Workflow)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(notificationsetting.FieldWorkflowID)
	}
	query.Where(predicate.NotificationSetting(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(workflow.NotificationSettingsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.WorkflowID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "workflow_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *WorkflowQuery) loadNotifications(ctx context.Context, query *NotificationQuery, nodes []*Workflow, init func(*Workflow), assign func(*Workflow, *Notification)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Workflow)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(notification.FieldWorkflowID)
	}
	query.Where(predicate.Notification(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(workflow.NotificationsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.WorkflowID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "workflow_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *WorkflowQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *WorkflowQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(workflow.Table, workflow.Columns, sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workflow.FieldID)
		for i := range fields {
			if fields[i] != workflow.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *WorkflowQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(workflow.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = workflow.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WorkflowGroupBy is the group-by builder for Workflow entities.
type WorkflowGroupBy struct {
	selector
	build *WorkflowQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *WorkflowGroupBy) Aggregate(fns ...AggregateFunc) *WorkflowGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *WorkflowGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WorkflowQuery, *WorkflowGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *WorkflowGroupBy) sqlScan(ctx context.Context, root *WorkflowQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// WorkflowSelect is the builder for selecting fields of Workflow entities.
type WorkflowSelect struct {
	*WorkflowQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *WorkflowSelect) Aggregate(fns ...AggregateFunc) *WorkflowSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *WorkflowSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WorkflowQuery, *WorkflowSelect](ctx, _s.WorkflowQuery, _s, _s.inters, v)
}

func (_s *WorkflowSelect) sqlScan(ctx context.Context, root *WorkflowQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
