// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"react-go-workflow/ent/predicate"
	"react-go-workflow/ent/workflow"
	"react-go-workflow/ent/workflowexecution"
	"react-go-workflow/ent/workflowversion"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// WorkflowVersionUpdate is the builder for updating WorkflowVersion entities.
type WorkflowVersionUpdate struct {
	config
	hooks    []Hook
	mutation *WorkflowVersionMutation
}

// Where appends a list predicates to the WorkflowVersionUpdate builder.
func (_u *WorkflowVersionUpdate) Where(ps ...predicate.WorkflowVersion) *WorkflowVersionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDateUpdated sets the "date_updated" field.
func (_u *WorkflowVersionUpdate) SetDateUpdated(v time.Time) *WorkflowVersionUpdate {
	_u.mutation.SetDateUpdated(v)
	return _u
}

// SetNillableDateUpdated sets the "date_updated" field if the given value is not nil.
func (_u *WorkflowVersionUpdate) SetNillableDateUpdated(v *time.Time) *WorkflowVersionUpdate {
	if v != nil {
		_u.SetDateUpdated(*v)
	}
	return _u
}

// ClearDateUpdated clears the value of the "date_updated" field.
func (_u *WorkflowVersionUpdate) ClearDateUpdated() *WorkflowVersionUpdate {
	_u.mutation.ClearDateUpdated()
	return _u
}

// SetWorkflowID sets the "workflow_id" field.
func (_u *WorkflowVersionUpdate) SetWorkflowID(v uuid.UUID) *WorkflowVersionUpdate {
	_u.mutation.SetWorkflowID(v)
	return _u
}

// SetNillableWorkflowID sets the "workflow_id" field if the given value is not nil.
func (_u *WorkflowVersionUpdate) SetNillableWorkflowID(v *uuid.UUID) *WorkflowVersionUpdate {
	if v != nil {
		_u.SetWorkflowID(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *WorkflowVersionUpdate) SetVersion(v int) *WorkflowVersionUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *WorkflowVersionUpdate) SetNillableVersion(v *int) *WorkflowVersionUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *WorkflowVersionUpdate) AddVersion(v int) *WorkflowVersionUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetSnapshot sets the "snapshot" field.
func (_u *WorkflowVersionUpdate) SetSnapshot(v map[string]interface{}) *WorkflowVersionUpdate {
	_u.mutation.SetSnapshot(v)
	return _u
}

// ClearSnapshot clears the value of the "snapshot" field.
func (_u *WorkflowVersionUpdate) ClearSnapshot() *WorkflowVersionUpdate {
	_u.mutation.ClearSnapshot()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *WorkflowVersionUpdate) SetPublishedAt(v time.Time) *WorkflowVersionUpdate {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *WorkflowVersionUpdate) SetNillablePublishedAt(v *time.Time) *WorkflowVersionUpdate {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// SetWorkflow sets the "workflow" edge to the Workflow entity.
func (_u *WorkflowVersionUpdate) SetWorkflow(v *Workflow) *WorkflowVersionUpdate {
	return _u.SetWorkflowID(v.ID)
}

// AddExecutionIDs adds the "executions" edge to the WorkflowExecution entity by IDs.
func (_u *WorkflowVersionUpdate) AddExecutionIDs(ids ...uuid.UUID) *WorkflowVersionUpdate {
	_u.mutation.AddExecutionIDs(ids...)
	return _u
}

// AddExecutions adds the "executions" edges to the WorkflowExecution entity.
func (_u *WorkflowVersionUpdate) AddExecutions(v ...*WorkflowExecution) *WorkflowVersionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddExecutionIDs(ids...)
}

// Mutation returns the WorkflowVersionMutation object of the builder.
func (_u *WorkflowVersionUpdate) Mutation() *WorkflowVersionMutation {
	return _u.mutation
}

// ClearWorkflow clears the "workflow" edge to the Workflow entity.
func (_u *WorkflowVersionUpdate) ClearWorkflow() *WorkflowVersionUpdate {
	_u.mutation.ClearWorkflow()
	return _u
}

// ClearExecutions clears all "executions" edges to the WorkflowExecution entity.
func (_u *WorkflowVersionUpdate) ClearExecutions() *WorkflowVersionUpdate {
	_u.mutation.ClearExecutions()
	return _u
}

// RemoveExecutionIDs removes the "executions" edge to WorkflowExecution entities by IDs.
func (_u *WorkflowVersionUpdate) RemoveExecutionIDs(ids ...uuid.UUID) *WorkflowVersionUpdate {
	_u.mutation.RemoveExecutionIDs(ids...)
	return _u
}

// RemoveExecutions removes "executions" edges to WorkflowExecution entities.
func (_u *WorkflowVersionUpdate) RemoveExecutions(v ...*WorkflowExecution) *WorkflowVersionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveExecutionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WorkflowVersionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkflowVersionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WorkflowVersionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkflowVersionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkflowVersionUpdate) check() error {
	if v, ok := _u.mutation.Version(); ok {
		if err := workflowversion.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "WorkflowVersion.version": %w`, err)}
		}
	}
	if _u.mutation.WorkflowCleared() && len(_u.mutation.WorkflowIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WorkflowVersion.workflow"`)
	}
	return nil
}

func (_u *WorkflowVersionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workflowversion.Table, workflowversion.Columns, sqlgraph.NewFieldSpec(workflowversion.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DateUpdated(); ok {
		_spec.SetField(workflowversion.FieldDateUpdated, field.TypeTime, value)
	}
	if _u.mutation.DateUpdatedCleared() {
		_spec.ClearField(workflowversion.FieldDateUpdated, field.TypeTime)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(workflowversion.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(workflowversion.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Snapshot(); ok {
		_spec.SetField(workflowversion.FieldSnapshot, field.TypeJSON, value)
	}
	if _u.mutation.SnapshotCleared() {
		_spec.ClearField(workflowversion.FieldSnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(workflowversion.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.WorkflowCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workflowversion.WorkflowTable,
			Columns: []string{workflowversion.WorkflowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkflowIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workflowversion.WorkflowTable,
			Columns: []string{workflowversion.WorkflowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ExecutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflowversion.ExecutionsTable,
			Columns: []string{workflowversion.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflowexecution.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedExecutionsIDs(); len(nodes) > 0 && !_u.mutation.ExecutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflowversion.ExecutionsTable,
			Columns: []string{workflowversion.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflowexecution.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ExecutionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflowversion.ExecutionsTable,
			Columns: []string{workflowversion.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflowexecution.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workflowversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WorkflowVersionUpdateOne is the builder for updating a single WorkflowVersion entity.
type WorkflowVersionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkflowVersionMutation
}

// SetDateUpdated sets the "date_updated" field.
func (_u *WorkflowVersionUpdateOne) SetDateUpdated(v time.Time) *WorkflowVersionUpdateOne {
	_u.mutation.SetDateUpdated(v)
	return _u
}

// SetNillableDateUpdated sets the "date_updated" field if the given value is not nil.
func (_u *WorkflowVersionUpdateOne) SetNillableDateUpdated(v *time.Time) *WorkflowVersionUpdateOne {
	if v != nil {
		_u.SetDateUpdated(*v)
	}
	return _u
}

// ClearDateUpdated clears the value of the "date_updated" field.
func (_u *WorkflowVersionUpdateOne) ClearDateUpdated() *WorkflowVersionUpdateOne {
	_u.mutation.ClearDateUpdated()
	return _u
}

// SetWorkflowID sets the "workflow_id" field.
func (_u *WorkflowVersionUpdateOne) SetWorkflowID(v uuid.UUID) *WorkflowVersionUpdateOne {
	_u.mutation.SetWorkflowID(v)
	return _u
}

// SetNillableWorkflowID sets the "workflow_id" field if the given value is not nil.
func (_u *WorkflowVersionUpdateOne) SetNillableWorkflowID(v *uuid.UUID) *WorkflowVersionUpdateOne {
	if v != nil {
		_u.SetWorkflowID(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *WorkflowVersionUpdateOne) SetVersion(v int) *WorkflowVersionUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *WorkflowVersionUpdateOne) SetNillableVersion(v *int) *WorkflowVersionUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *WorkflowVersionUpdateOne) AddVersion(v int) *WorkflowVersionUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetSnapshot sets the "snapshot" field.
func (_u *WorkflowVersionUpdateOne) SetSnapshot(v map[string]interface{}) *WorkflowVersionUpdateOne {
	_u.mutation.SetSnapshot(v)
	return _u
}

// ClearSnapshot clears the value of the "snapshot" field.
func (_u *WorkflowVersionUpdateOne) ClearSnapshot() *WorkflowVersionUpdateOne {
	_u.mutation.ClearSnapshot()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *WorkflowVersionUpdateOne) SetPublishedAt(v time.Time) *WorkflowVersionUpdateOne {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *WorkflowVersionUpdateOne) SetNillablePublishedAt(v *time.Time) *WorkflowVersionUpdateOne {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// SetWorkflow sets the "workflow" edge to the Workflow entity.
func (_u *WorkflowVersionUpdateOne) SetWorkflow(v *Workflow) *WorkflowVersionUpdateOne {
	return _u.SetWorkflowID(v.ID)
}

// AddExecutionIDs adds the "executions" edge to the WorkflowExecution entity by IDs.
func (_u *WorkflowVersionUpdateOne) AddExecutionIDs(ids ...uuid.UUID) *WorkflowVersionUpdateOne {
	_u.mutation.AddExecutionIDs(ids...)
	return _u
}

// AddExecutions adds the "executions" edges to the WorkflowExecution entity.
func (_u *WorkflowVersionUpdateOne) AddExecutions(v ...*WorkflowExecution) *WorkflowVersionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddExecutionIDs(ids...)
}

// Mutation returns the WorkflowVersionMutation object of the builder.
func (_u *WorkflowVersionUpdateOne) Mutation() *WorkflowVersionMutation {
	return _u.mutation
}

// ClearWorkflow clears the "workflow" edge to the Workflow entity.
func (_u *WorkflowVersionUpdateOne) ClearWorkflow() *WorkflowVersionUpdateOne {
	_u.mutation.ClearWorkflow()
	return _u
}

// ClearExecutions clears all "executions" edges to the WorkflowExecution entity.
func (_u *WorkflowVersionUpdateOne) ClearExecutions() *WorkflowVersionUpdateOne {
	_u.mutation.ClearExecutions()
	return _u
}

// RemoveExecutionIDs removes the "executions" edge to WorkflowExecution entities by IDs.
func (_u *WorkflowVersionUpdateOne) RemoveExecutionIDs(ids ...uuid.UUID) *WorkflowVersionUpdateOne {
	_u.mutation.RemoveExecutionIDs(ids...)
	return _u
}

// RemoveExecutions removes "executions" edges to WorkflowExecution entities.
func (_u *WorkflowVersionUpdateOne) RemoveExecutions(v ...*WorkflowExecution) *WorkflowVersionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveExecutionIDs(ids...)
}

// Where appends a list predicates to the WorkflowVersionUpdate builder.
func (_u *WorkflowVersionUpdateOne) Where(ps ...predicate.WorkflowVersion) *WorkflowVersionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WorkflowVersionUpdateOne) Select(field string, fields ...string) *WorkflowVersionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WorkflowVersion entity.
func (_u *WorkflowVersionUpdateOne) Save(ctx context.Context) (*WorkflowVersion, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkflowVersionUpdateOne) SaveX(ctx context.Context) *WorkflowVersion {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WorkflowVersionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkflowVersionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkflowVersionUpdateOne) check() error {
	if v, ok := _u.mutation.Version(); ok {
		if err := workflowversion.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "WorkflowVersion.version": %w`, err)}
		}
	}
	if _u.mutation.WorkflowCleared() && len(_u.mutation.WorkflowIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WorkflowVersion.workflow"`)
	}
	return nil
}

func (_u *WorkflowVersionUpdateOne) sqlSave(ctx context.Context) (_node *WorkflowVersion, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workflowversion.Table, workflowversion.Columns, sqlgraph.NewFieldSpec(workflowversion.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WorkflowVersion.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workflowversion.FieldID)
		for _, f := range fields {
			if !workflowversion.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workflowversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DateUpdated(); ok {
		_spec.SetField(workflowversion.FieldDateUpdated, field.TypeTime, value)
	}
	if _u.mutation.DateUpdatedCleared() {
		_spec.ClearField(workflowversion.FieldDateUpdated, field.TypeTime)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(workflowversion.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(workflowversion.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Snapshot(); ok {
		_spec.SetField(workflowversion.FieldSnapshot, field.TypeJSON, value)
	}
	if _u.mutation.SnapshotCleared() {
		_spec.ClearField(workflowversion.FieldSnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(workflowversion.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.WorkflowCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workflowversion.WorkflowTable,
			Columns: []string{workflowversion.WorkflowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkflowIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workflowversion.WorkflowTable,
			Columns: []string{workflowversion.WorkflowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ExecutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflowversion.ExecutionsTable,
			Columns: []string{workflowversion.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflowexecution.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedExecutionsIDs(); len(nodes) > 0 && !_u.mutation.ExecutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflowversion.ExecutionsTable,
			Columns: []string{workflowversion.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflowexecution.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ExecutionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflowversion.ExecutionsTable,
			Columns: []string{workflowversion.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflowexecution.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &WorkflowVersion{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workflowversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
