// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"react-go-workflow/ent/workflow"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Workflow is the model entity for the Workflow schema.
type Workflow struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// DateCreated holds the value of the "date_created" field.
	DateCreated time.Time `json:"date_created,omitempty"`
	// DateUpdated holds the value of the "date_updated" field.
	DateUpdated *time.Time `json:"date_updated,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Status holds the value of the "status" field.
	Status workflow.Status `json:"status,omitempty"`
	// TriggerConfig holds the value of the "trigger_config" field.
	TriggerConfig map[string]interface{} `json:"trigger_config,omitempty"`
	// InputSchema holds the value of the "input_schema" field.
	InputSchema map[string]interface{} `json:"input_schema,omitempty"`
	// OutputSchema holds the value of the "output_schema" field.
	OutputSchema map[string]interface{} `json:"output_schema,omitempty"`
	// WebhookSlug holds the value of the "webhook_slug" field.
	WebhookSlug *string `json:"webhook_slug,omitempty"`
	// Concurrency holds the value of the "concurrency" field.
	Concurrency workflow.Concurrency `json:"concurrency,omitempty"`
	// TimeoutSeconds holds the value of the "timeout_seconds" field.
	TimeoutSeconds *int `json:"timeout_seconds,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the WorkflowQuery when eager-loading is set.
	Edges        WorkflowEdges `json:"edges"`
	selectValues sql.SelectValues
}

// WorkflowEdges holds the relations/edges for other nodes in the graph.
type WorkflowEdges struct {
	// Steps holds the value of the steps edge.
	Steps []*Step `json:"steps,omitempty"`
	// Edges holds the value of the edges edge.
	Edges []*Edge `json:"edges,omitempty"`
	// CanvasNotes holds the value of the canvas_notes edge.
	CanvasNotes []*CanvasNote `json:"canvas_notes,omitempty"`
	// Versions holds the value of the versions edge.
	Versions []*WorkflowVersion `json:"versions,omitempty"`
	// Executions holds the value of the executions edge.
	Executions []*WorkflowExecution `json:"executions,omitempty"`
	// NotificationSettings holds the value of the notification_settings edge.
	NotificationSettings []*NotificationSetting `json:"notification_settings,omitempty"`
	// Notifications holds the value of the notifications edge.
	Notifications []*Notification `json:"notifications,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [7]bool
}

// StepsOrErr returns the Steps value or an error if the edge
// was not loaded in eager-loading.
func (e WorkflowEdges) StepsOrErr() ([]*Step, error) {
	if e.loadedTypes[0] {
		return e.Steps, nil
	}
	return nil, &NotLoadedError{edge: "steps"}
}

// EdgesOrErr returns the Edges value or an error if the edge
// was not loaded in eager-loading.
func (e WorkflowEdges) EdgesOrErr() ([]*Edge, error) {
	if e.loadedTypes[1] {
		return e.Edges, nil
	}
	return nil, &NotLoadedError{edge: "edges"}
}

// CanvasNotesOrErr returns the CanvasNotes value or an error if the edge
// was not loaded in eager-loading.
func (e WorkflowEdges) CanvasNotesOrErr() ([]*CanvasNote, error) {
	if e.loadedTypes[2] {
		return e.CanvasNotes, nil
	}
	return nil, &NotLoadedError{edge: "canvas_notes"}
}

// VersionsOrErr returns the Versions value or an error if the edge
// was not loaded in eager-loading.
func (e WorkflowEdges) VersionsOrErr() ([]*WorkflowVersion, error) {
	if e.loadedTypes[3] {
		return e.Versions, nil
	}
	return nil, &NotLoadedError{edge: "versions"}
}

// ExecutionsOrErr returns the Executions value or an error if the edge
// was not loaded in eager-loading.
func (e WorkflowEdges) ExecutionsOrErr() ([]*WorkflowExecution, error) {
	if e.loadedTypes[4] {
		return e.Executions, nil
	}
	return nil, &NotLoadedError{edge: "executions"}
}

// NotificationSettingsOrErr returns the NotificationSettings value or an error if the edge
// was not loaded in eager-loading.
func (e WorkflowEdges) NotificationSettingsOrErr() ([]*NotificationSetting, error) {
	if e.loadedTypes[5] {
		return e.NotificationSettings, nil
	}
	return nil, &NotLoadedError{edge: "notification_settings"}
}

// NotificationsOrErr returns the Notifications value or an error if the edge
// was not loaded in eager-loading.
func (e WorkflowEdges) NotificationsOrErr() ([]*Notification, error) {
	if e.loadedTypes[6] {
		return e.Notifications, nil
	}
	return nil, &NotLoadedError{edge: "notifications"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Workflow) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case workflow.FieldTriggerConfig, workflow.FieldInputSchema, workflow.FieldOutputSchema:
			values[i] = new([]byte)
		case workflow.FieldTimeoutSeconds:
			values[i] = new(sql.NullInt64)
		case workflow.FieldName, workflow.FieldDescription, workflow.FieldStatus, workflow.FieldWebhookSlug, workflow.FieldConcurrency:
			values[i] = new(sql.NullString)
		case workflow.FieldDateCreated, workflow.FieldDateUpdated:
			values[i] = new(sql.NullTime)
		case workflow.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Workflow fields.
func (_m *Workflow) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case workflow.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case workflow.FieldDateCreated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_created", values[i])
			} else if value.Valid {
				_m.DateCreated = value.Time
			}
		case workflow.FieldDateUpdated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_updated", values[i])
			} else if value.Valid {
				_m.DateUpdated = new(time.Time)
				*_m.DateUpdated = value.Time
			}
		case workflow.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case workflow.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case workflow.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = workflow.Status(value.String)
			}
		case workflow.FieldTriggerConfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field trigger_config", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.TriggerConfig); err != nil {
					return fmt.Errorf("unmarshal field trigger_config: %w", err)
				}
			}
		case workflow.FieldInputSchema:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field input_schema", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.InputSchema); err != nil {
					return fmt.Errorf("unmarshal field input_schema: %w", err)
				}
			}
		case workflow.FieldOutputSchema:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field output_schema", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.OutputSchema); err != nil {
					return fmt.Errorf("unmarshal field output_schema: %w", err)
				}
			}
		case workflow.FieldWebhookSlug:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field webhook_slug", values[i])
			} else if value.Valid {
				_m.WebhookSlug = new(string)
				*_m.WebhookSlug = value.String
			}
		case workflow.FieldConcurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field concurrency", values[i])
			} else if value.Valid {
				_m.Concurrency = workflow.Concurrency(value.String)
			}
		case workflow.FieldTimeoutSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field timeout_seconds", values[i])
			} else if value.Valid {
				_m.TimeoutSeconds = new(int)
				*_m.TimeoutSeconds = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Workflow.
// This includes values selected through modifiers, order, etc.
func (_m *Workflow) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySteps queries the "steps" edge of the Workflow entity.
func (_m *Workflow) QuerySteps() *StepQuery {
	return NewWorkflowClient(_m.config).QuerySteps(_m)
}

// QueryEdges queries the "edges" edge of the Workflow entity.
func (_m *Workflow) QueryEdges() *EdgeQuery {
	return NewWorkflowClient(_m.config).QueryEdges(_m)
}

// QueryCanvasNotes queries the "canvas_notes" edge of the Workflow entity.
func (_m *Workflow) QueryCanvasNotes() *CanvasNoteQuery {
	return NewWorkflowClient(_m.config).QueryCanvasNotes(_m)
}

// QueryVersions queries the "versions" edge of the Workflow entity.
func (_m *Workflow) QueryVersions() *WorkflowVersionQuery {
	return NewWorkflowClient(_m.config).QueryVersions(_m)
}

// QueryExecutions queries the "executions" edge of the Workflow entity.
func (_m *Workflow) QueryExecutions() *WorkflowExecutionQuery {
	return NewWorkflowClient(_m.config).QueryExecutions(_m)
}

// QueryNotificationSettings queries the "notification_settings" edge of the Workflow entity.
func (_m *Workflow) QueryNotificationSettings() *NotificationSettingQuery {
	return NewWorkflowClient(_m.config).QueryNotificationSettings(_m)
}

// QueryNotifications queries the "notifications" edge of the Workflow entity.
func (_m *Workflow) QueryNotifications() *NotificationQuery {
	return NewWorkflowClient(_m.config).QueryNotifications(_m)
}

// Update returns a builder for updating this Workflow.
// Note that you need to call Workflow.Unwrap() before calling this method if this Workflow
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Workflow) Update() *WorkflowUpdateOne {
	return NewWorkflowClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Workflow entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Workflow) Unwrap() *Workflow {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Workflow is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Workflow) String() string {
	var builder strings.Builder
	builder.WriteString("Workflow(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("date_created=")
	builder.WriteString(_m.DateCreated.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DateUpdated; v != nil {
		builder.WriteString("date_updated=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("trigger_config=")
	builder.WriteString(fmt.Sprintf("%v", _m.TriggerConfig))
	builder.WriteString(", ")
	builder.WriteString("input_schema=")
	builder.WriteString(fmt.Sprintf("%v", _m.InputSchema))
	builder.WriteString(", ")
	builder.WriteString("output_schema=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutputSchema))
	builder.WriteString(", ")
	if v := _m.WebhookSlug; v != nil {
		builder.WriteString("webhook_slug=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("concurrency=")
	builder.WriteString(fmt.Sprintf("%v", _m.Concurrency))
	builder.WriteString(", ")
	if v := _m.TimeoutSeconds; v != nil {
		builder.WriteString("timeout_seconds=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Workflows is a parsable slice of Workflow.
type Workflows []*Workflow
