// Code generated by ent, DO NOT EDIT.

package notificationsetting

import (
	"fmt"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the notificationsetting type in the database.
	Label = "notification_setting"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDateCreated holds the string denoting the date_created field in the database.
	FieldDateCreated = "date_created"
	// FieldDateUpdated holds the string denoting the date_updated field in the database.
	FieldDateUpdated = "date_updated"
	// FieldWorkflowID holds the string denoting the workflow_id field in the database.
	FieldWorkflowID = "workflow_id"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldChannel holds the string denoting the channel field in the database.
	FieldChannel = "channel"
	// FieldConfig holds the string denoting the config field in the database.
	FieldConfig = "config"
	// FieldNotifyOn holds the string denoting the notify_on field in the database.
	FieldNotifyOn = "notify_on"
	// EdgeWorkflow holds the string denoting the workflow edge name in mutations.
	EdgeWorkflow = "workflow"
	// Table holds the table name of the notificationsetting in the database.
	Table = "notification_settings"
	// WorkflowTable is the table that holds the workflow relation/edge.
	WorkflowTable = "notification_settings"
	// WorkflowInverseTable is the table name for the Workflow entity.
	// It exists in this package in order to avoid circular dependency with the "workflow" package.
	WorkflowInverseTable = "workflows"
	// WorkflowColumn is the table column denoting the workflow relation/edge.
	WorkflowColumn = "workflow_id"
)

// Columns holds all SQL columns for notificationsetting fields.
var Columns = []string{
	FieldID,
	FieldDateCreated,
	FieldDateUpdated,
	FieldWorkflowID,
	FieldEnabled,
	FieldChannel,
	FieldConfig,
	FieldNotifyOn,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "react-go-workflow/ent/runtime"
var (
	Hooks [2]ent.Hook
	// DefaultDateCreated holds the default value on creation for the "date_created" field.
	DefaultDateCreated func() time.Time
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Channel defines the type for the "channel" enum field.
type Channel string

// Channel values.
const (
	ChannelInApp   Channel = "in_app"
	ChannelEmail   Channel = "email"
	ChannelWebhook Channel = "webhook"
)

func (c Channel) String() string {
	return string(c)
}

// ChannelValidator is a validator for the "channel" field enum values. It is called by the builders before save.
func ChannelValidator(c Channel) error {
	switch c {
	case ChannelInApp, ChannelEmail, ChannelWebhook:
		return nil
	default:
		return fmt.Errorf("notificationsetting: invalid enum value for channel field: %q", c)
	}
}

// NotifyOn defines the type for the "notify_on" enum field.
type NotifyOn string

// NotifyOnFailure is the default value of the NotifyOn enum.
const DefaultNotifyOn = NotifyOnFailure

// NotifyOn values.
const (
	NotifyOnFailure NotifyOn = "failure"
	NotifyOnSuccess NotifyOn = "success"
	NotifyOnAll     NotifyOn = "all"
)

func (no NotifyOn) String() string {
	return string(no)
}

// NotifyOnValidator is a validator for the "notify_on" field enum values. It is called by the builders before save.
func NotifyOnValidator(no NotifyOn) error {
	switch no {
	case NotifyOnFailure, NotifyOnSuccess, NotifyOnAll:
		return nil
	default:
		return fmt.Errorf("notificationsetting: invalid enum value for notify_on field: %q", no)
	}
}

// OrderOption defines the ordering options for the NotificationSetting queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDateCreated orders the results by the date_created field.
func ByDateCreated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateCreated, opts...).ToFunc()
}

// ByDateUpdated orders the results by the date_updated field.
func ByDateUpdated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateUpdated, opts...).ToFunc()
}

// ByWorkflowID orders the results by the workflow_id field.
func ByWorkflowID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkflowID, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByChannel orders the results by the channel field.
func ByChannel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannel, opts...).ToFunc()
}

// ByNotifyOn orders the results by the notify_on field.
func ByNotifyOn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotifyOn, opts...).ToFunc()
}

// ByWorkflowField orders the results by workflow field.
func ByWorkflowField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newWorkflowStep(), sql.OrderByField(field, opts...))
	}
}
func newWorkflowStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(WorkflowInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, WorkflowTable, WorkflowColumn),
	)
}
