// Code generated by ent, DO NOT EDIT.

package notificationsetting

import (
	"react-go-workflow/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldLTE(FieldID, id))
}

// DateCreated applies equality check predicate on the "date_created" field. It's identical to DateCreatedEQ.
func DateCreated(v time.Time) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldDateCreated, v))
}

// DateUpdated applies equality check predicate on the "date_updated" field. It's identical to DateUpdatedEQ.
func DateUpdated(v time.Time) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldDateUpdated, v))
}

// WorkflowID applies equality check predicate on the "workflow_id" field. It's identical to WorkflowIDEQ.
func WorkflowID(v uuid.UUID) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldWorkflowID, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldEnabled, v))
}

// DateCreatedEQ applies the EQ predicate on the "date_created" field.
func DateCreatedEQ(v time.Time) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldDateCreated, v))
}

// DateCreatedNEQ applies the NEQ predicate on the "date_created" field.
func DateCreatedNEQ(v time.Time) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNEQ(FieldDateCreated, v))
}

// DateCreatedIn applies the In predicate on the "date_created" field.
func DateCreatedIn(vs ...time.Time) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldIn(FieldDateCreated, vs...))
}

// DateCreatedNotIn applies the NotIn predicate on the "date_created" field.
func DateCreatedNotIn(vs ...time.Time) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNotIn(FieldDateCreated, vs...))
}

// DateCreatedGT applies the GT predicate on the "date_created" field.
func DateCreatedGT(v time.Time) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldGT(FieldDateCreated, v))
}

// DateCreatedGTE applies the GTE predicate on the "date_created" field.
func DateCreatedGTE(v time.Time) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldGTE(FieldDateCreated, v))
}

// DateCreatedLT applies the LT predicate on the "date_created" field.
func DateCreatedLT(v time.Time) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldLT(FieldDateCreated, v))
}

// DateCreatedLTE applies the LTE predicate on the "date_created" field.
func DateCreatedLTE(v time.Time) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldLTE(FieldDateCreated, v))
}

// DateUpdatedEQ applies the EQ predicate on the "date_updated" field.
func DateUpdatedEQ(v time.Time) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldDateUpdated, v))
}

// DateUpdatedNEQ applies the NEQ predicate on the "date_updated" field.
func DateUpdatedNEQ(v time.Time) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNEQ(FieldDateUpdated, v))
}

// DateUpdatedIn applies the In predicate on the "date_updated" field.
func DateUpdatedIn(vs ...time.Time) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldIn(FieldDateUpdated, vs...))
}

// DateUpdatedNotIn applies the NotIn predicate on the "date_updated" field.
func DateUpdatedNotIn(vs ...time.Time) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNotIn(FieldDateUpdated, vs...))
}

// DateUpdatedGT applies the GT predicate on the "date_updated" field.
func DateUpdatedGT(v time.Time) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldGT(FieldDateUpdated, v))
}

// DateUpdatedGTE applies the GTE predicate on the "date_updated" field.
func DateUpdatedGTE(v time.Time) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldGTE(FieldDateUpdated, v))
}

// DateUpdatedLT applies the LT predicate on the "date_updated" field.
func DateUpdatedLT(v time.Time) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldLT(FieldDateUpdated, v))
}

// DateUpdatedLTE applies the LTE predicate on the "date_updated" field.
func DateUpdatedLTE(v time.Time) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldLTE(FieldDateUpdated, v))
}

// DateUpdatedIsNil applies the IsNil predicate on the "date_updated" field.
func DateUpdatedIsNil() predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldIsNull(FieldDateUpdated))
}

// DateUpdatedNotNil applies the NotNil predicate on the "date_updated" field.
func DateUpdatedNotNil() predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNotNull(FieldDateUpdated))
}

// WorkflowIDEQ applies the EQ predicate on the "workflow_id" field.
func WorkflowIDEQ(v uuid.UUID) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldWorkflowID, v))
}

// WorkflowIDNEQ applies the NEQ predicate on the "workflow_id" field.
func WorkflowIDNEQ(v uuid.UUID) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNEQ(FieldWorkflowID, v))
}

// WorkflowIDIn applies the In predicate on the "workflow_id" field.
func WorkflowIDIn(vs ...uuid.UUID) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldIn(FieldWorkflowID, vs...))
}

// WorkflowIDNotIn applies the NotIn predicate on the "workflow_id" field.
func WorkflowIDNotIn(vs ...uuid.UUID) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNotIn(FieldWorkflowID, vs...))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNEQ(FieldEnabled, v))
}

// ChannelEQ applies the EQ predicate on the "channel" field.
func ChannelEQ(v Channel) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldChannel, v))
}

// ChannelNEQ applies the NEQ predicate on the "channel" field.
func ChannelNEQ(v Channel) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNEQ(FieldChannel, v))
}

// ChannelIn applies the In predicate on the "channel" field.
func ChannelIn(vs ...Channel) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldIn(FieldChannel, vs...))
}

// ChannelNotIn applies the NotIn predicate on the "channel" field.
func ChannelNotIn(vs ...Channel) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNotIn(FieldChannel, vs...))
}

// ConfigIsNil applies the IsNil predicate on the "config" field.
func ConfigIsNil() predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldIsNull(FieldConfig))
}

// ConfigNotNil applies the NotNil predicate on the "config" field.
func ConfigNotNil() predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNotNull(FieldConfig))
}

// NotifyOnEQ applies the EQ predicate on the "notify_on" field.
func NotifyOnEQ(v NotifyOn) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldNotifyOn, v))
}

// NotifyOnNEQ applies the NEQ predicate on the "notify_on" field.
func NotifyOnNEQ(v NotifyOn) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNEQ(FieldNotifyOn, v))
}

// NotifyOnIn applies the In predicate on the "notify_on" field.
func NotifyOnIn(vs ...NotifyOn) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldIn(FieldNotifyOn, vs...))
}

// NotifyOnNotIn applies the NotIn predicate on the "notify_on" field.
func NotifyOnNotIn(vs ...NotifyOn) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNotIn(FieldNotifyOn, vs...))
}

// HasWorkflow applies the HasEdge predicate on the "workflow" edge.
func HasWorkflow() predicate.NotificationSetting {
	return predicate.NotificationSetting(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, WorkflowTable, WorkflowColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWorkflowWith applies the HasEdge predicate on the "workflow" edge with a given conditions (other predicates).
func HasWorkflowWith(preds ...predicate.Workflow) predicate.NotificationSetting {
	return predicate.NotificationSetting(func(s *sql.Selector) {
		step := newWorkflowStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.NotificationSetting) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.NotificationSetting) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.NotificationSetting) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.NotPredicates(p))
}
